### DISCUSSION TITLE
Questions about deployments

### DISCUSSION THREAD

**Discussion by sam-phinizy** [skypilot-org/skypilot#1693] [General]
Hi there! 

First off just wanted to say this is very impressive. It's a tool that I have always wanted but never got around to making. So thanks!

I had a question about how configurable environments are. My current work is an AWS shop and we're thinking of using skypilot for some adhoc data analysis. I skimmed through the docs and might have missed this but is it possible to specify things such as Security Group or VPC the EC2 instances run in?

**Comment by concretevitamin** [comment]
Hello @sam-phinizy! Yes, you can bring your own VPC on AWS. We currently support selecting your VPC by name (the name column in console). You can create a `~/.sky/config.yaml` file with the following contents:
```yaml
aws:
  # The VPC to use in each region.
  #
  # If this is set, any region without a unique VPC with this name will not be
  # able to launch SkyPilot nodes. SkyPilot's failover will still properly
  # function to look for such an eligible region.
  #
  # Optional; default: None (SkyPilot will use the default VPC in each region).
  vpc_name: <FILL IN YOUR VPC NAME>
```
This was added quite recently in #1512 and we've been pilot testing it with some users, which is why docs haven't been added. 

To chat more about your needs feel free to join our Slack or shoot us an email if you'd like!
