### ISSUE TITLE
[Storage] Not select the correct bucket provider when the cloud is specified

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1068]
The following yaml will upload the `~/tmp` to the S3 bucket, instead of deciding by the cloud specified in resources.
```
resources:
  cloud: gcp

file_mounts:
  /test-path:
    name: sky-storage-test-tmp
    source: ~/tmp
    mode: COPY
```
