### ISSUE TITLE
[Storage] VM loses S3 mount after stop/start

### ISSUE THREAD

**Issue by franklsf95** [skypilot-org/skypilot#1203]
To reproduce: make `cluster.yml`:

```
resources:
  cloud: aws
  instance_type: g4dn.xlarge
  disk_size: 500

workdir: .

num_nodes: 4

file_mounts:
  /dataset:
    source: s3://raysort-kl
    store: s3

setup: |
  echo "Hello, SkyPilot!"

run: |
  echo "Hello, SkyPilot!"
```

Then

```
sky launch cluster.yml -c g4
# login, verify content of /dataset is present
sky stop -y g4
sky start -y g4
# login, /dataset becomes empty
```

I _think_ this also happens on a single-node VM but I haven't verified it yet.
