### ISSUE TITLE
Incorrect SKY_NODE_RANK on nodes

### ISSUE THREAD

**Issue by iojw** [skypilot-org/skypilot#1206]
I would like to run a command only on the head node when the SkyPilot cluster launches. However, the `SKY_NODE_RANK` environment variable does not have the expected value of 0 on the head node on AWS.

Here is an example config that reproduces this:
```
resources:
  accelerators: T4:1
  cloud: aws
  disk_size: 1024

workdir: .

num_nodes: 4

run: |
  echo $SKY_NODE_RANK
```

Launching this cluster, you can observe that `SKY_NODE_RANK` is printed as 0 on worker nodes based on their IP addresses.

Use case: I would like to run distributed training using ludwig and ray. Since ludwig uses ray for the distributed training, the `ludwig train` command has to be executed on the ray head node.
