### ISSUE TITLE
[Onprem] Add ability to specify custom ports for ssh

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1210]
Currently sky onprem assumes port 22 for ssh access. However, servers may use different ports, ssh services behind a load balancer may use different ports on the same IP and local mode container (#968, #1165) may run on ports other than 22 if the user already has a ssh server running.

Implementing this would require modifying the [onprem YAML](https://skypilot.readthedocs.io/en/latest/reference/local/setup.html#publishing-cluster-yaml) to be support colon separated IPs like:
```
cluster:
  ips: [my.local.cluster.hostname:22, 3.20.226.96:27015, 3.143.112.6:10000]
  name: my-local-cluster

auth:
  ssh_user: PLACEHOLDER
  ssh_private_key: PLACEHOLDER

python: /usr/bin/python3
```
If port is not specified, then we should default to port 22.

**Comment by concretevitamin** [comment]
In this format,
```
cluster:
  ips: [my.local.cluster.hostname:22, 3.20.226.96:27015, 3.143.112.6:10000]
```
it's not clear what these ports are used for.  Before we implement this, can we survey how other systems support SSH ports?

Also, is this related to the "local mode", or is this a nice-to-have for the on-prem mode?

**Comment by romilbhardwaj** [comment]
> it's not clear what these ports are used for. Before we implement this, can we survey how other systems support SSH ports?

Good point - some systems (e.g. k8s services) use a new yaml field for each port to be exposed on the service:

```
ports:
  - name: http
    protocol: TCP
    port: 80
```

`IP:PORT` appealed to me because (a) it is concise (b) we have multiple IP addresses and each can have a different port. It's also commonly used in specifying sockets (such as for http). But I agree, we should look at other systems to before finalizing this.

> Also, is this related to the "local mode", or is this a nice-to-have for the on-prem mode?

It's both, but largely a necessity for "local mode". If my local machine already has port 22 used by something else, our current implementation won't work.
