### ISSUE TITLE
[Onprem] User hot-swapping fails silently

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1214]
Say I `sky launch -c onprem whoami_task.yaml` with this onprem yaml at `~/.sky/local/onprem.yaml`:

```
cluster:
  ips:
  - 35.86.96.195
  name: onprem

auth:
  ssh_user: ubuntu
  ssh_private_key: ~/.ssh/romilb.pem

python: /usr/bin/python3
```

Output is:
```
(minimal pid=32792) ubuntu
```

Now say I have another user on my onprem machine that I want to use for submitting future tasks. If I change `ssh_user` in onprem.yaml to `ssh_user: test` and run `sky launch -c onprem whoami_task.yaml`, output is still the same:
```
(minimal pid=32792) ubuntu
```

The user should have changed to `test`, but tasks are still being run as `ubuntu` user. We should throw up a warning/error instead of failing silently.
