### ISSUE TITLE
[TPU VM] ray status shows weird resource number

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1262]
After launching a `tpu-v3-32` instance with `sky launch -c test-tpuvm ./test.yaml`, `sky exec test-tpuvm ./test.yaml` multiple times, and `sky cancel test-tpuvm -a`, the `ray status` on the VM becomes quite weird with negative resource number in the following output. Do you have an idea of what happens here @infwinston ?
```
resources:
  accelerators: tpu-v3-32
  accelerator_args:
    tpu_vm: true
  use_spot: false

run: |
  echo hi
  sleep 120000
```
```
ay status
======== Autoscaler status: 2022-10-17 18:09:01.991178 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray_head_default
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 -1.5/192.0 CPU (0.0 used of 1.5 reserved in placement groups)
 0.00/923.305 GiB memory
 0.00/399.694 GiB object_store_memory
 -3.0/4.0 tpu-v3-32 (0.0 used of 3.0 reserved in placement groups)
```
