### ISSUE TITLE
[Storage] Leakage of storage with persistent=False

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1280]
Our storage is not linked with the cluster or task, so when the job finishes or the cluster is terminated, the storage will not be deleted even if the `persistent=False` is set.

```
# test.yaml
file_mounts:
  /dst:
    name: skypilot-zhwu-test-storage-persistent
    source: ~/tmpdir
    persistent: False

run: |
  echo hi
```

```
sky launch -c test-storage ./test.yaml
sky down test-storage
sky storage ls
```

This should be also related to #1203, as we need to store the storage information in the clusters' metadata.
Also, the `autodown` may also cause leakage for the storage, even after we add the info to the metadata.
cc @romilbhardwaj @michaelzhiluo
