### ISSUE TITLE
Support passing multiple `image_id`, one per region

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1345]
From user, whose app requires a specific Ubuntu 18.04 version, and does not support the latest 20.04 we use:

> An alternative could be to allow specifying image_id as a mapping from region to AMI so that at least the user won’t be limited to specifying a fixed region. This would be more flexible (esp if user wants to use custom AMIs) but a bit more work on the user’s side.

Previously, @pounde also requested this feature.

-----

Proposal:
```
resources:
  image_id:
    us-east-1: <find your us-east-1 AMI>
    us-west-1: <find your us-west-1 AMI>
```
where SkyPilot will restrict itself to provision in these regions only.
