### ISSUE TITLE
Support auto-selecting `image_id` by OS version

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1346]
From user, whose app requires a specific Ubuntu 18.04 version, and does not support the latest 20.04 we use:

> Is there a way to specify the desired ubuntu version of the AWS AMI without specifying the AMI explicitly (basically have Sky find the compatible AMI for me)?
I’m trying to debug if some cryptic MPI errors is due to incompatibility between the ubuntu version (18.04) of singularity image (similar to docker) and the host ubuntu (20.04).

> indeed I need to make sure the OS version is matching, so confirming the utility of this image id customization feature for me.

This is related to #1345, but different.

-------

Sketching a potential interface, while many are possible:
```
resources:
  versions:  # These are filters for image_id's (at least we can start with AMIs).
    ubuntu: 18.04
    cuda: 11.6
```
