### ISSUE TITLE
Error when restarting cluster

### ISSUE THREAD

**Issue by pschafhalter** [skypilot-org/skypilot#1517]
Hi, I'm running into the following error when restarting a cluster: `ModuleNotFoundError: No module named 'sky'`.
Steps to reproduce:
1. `sky launch -C my_cluster config.yaml`
2. `sky stop my_cluster`
3. `sky start my_cluster`

The instance is successfully provisioned on AWS, and I am able to SSH using the IP address. I'm not sure if this is relevant, but I noticed that after running `sky start` and SSHing, the terminal would not be running inside an active Conda environment.

I'm also using the AWS Deep Learning AMI and storing data in S3.

Full error log:
```
Restarting 1 cluster: sky-b4da-peter. Proceed? [Y/n]:
I 12-13 13:58:55 cloud_vm_ray_backend.py:903] To view detailed progress: tail -n100 -f /home/peter/sky_logs/sky-2022-12-13-13-58-55-599628/provision.log
I 12-13 13:58:55 cloud_vm_ray_backend.py:744] Cluster 'sky-b4da-peter' (status: STOPPED) was previously launched in AWS (us-west-2). Relaunching in that region.
I 12-13 13:58:56 cloud_vm_ray_backend.py:1152] Launching on AWS us-west-2 (us-west-2a,us-west-2b,us-west-2c,us-west-2d)
I 12-13 14:00:13 log_utils.py:45] Head node is up.
I 12-13 14:00:47 cloud_vm_ray_backend.py:996] Successfully provisioned or found existing VM.
E 12-13 14:00:48 subprocess_utils.py:69] Traceback (most recent call last):
E 12-13 14:00:48 subprocess_utils.py:69]   File "<string>", line 1, in <module>
E 12-13 14:00:48 subprocess_utils.py:69] ModuleNotFoundError: No module named 'sky'
E 12-13 14:00:48 subprocess_utils.py:69]
sky.exceptions.CommandError: Command python3 -u -c 'import os;from sky.skylet import job_lib, log_lib;job_lib.fail_all_jobs_in_progress()' failed with return code 1.
Failed to set previously in-progress jobs to FAILED
```

**Comment by Michaelvll** [comment]
Thank you for reporting the issue @pschafhalter! The SkyPilot runtime seems to have been wrongly set up on your remote cluster. Do you mind sharing the resources field of your `config.yaml` or the `image_id` you are using for the cluster to make it easier for us to debug the problem? 

PS, I tried the latest master branch d97ffed6, with the default AMI, but failed to reproduce the issue.

**Comment by pschafhalter** [comment]
Here's my YAML. I've changed the name of the python script and the S3 bucket. I believe I've run into the same issue with other instance types, so it might be a problem with the AMI.

```yaml
resources:
  cloud: aws
  instance_type: p4de.24xlarge
  region: us-west-2
  image_id: ami-0fe5af21074ad2a10  # Deep learning AMI with CUDA 11.6

workdir: .

file_mounts:
  /data:
    name: my_s3_bucket
    mode: MOUNT

setup: |
  ls data/  # Set up the S3 bucket
  bash scripts/setup.sh

run: |
  python3 my_script.py
```
