### ISSUE TITLE
Files not uploading to S3

### ISSUE THREAD

**Issue by pschafhalter** [skypilot-org/skypilot#1601]
When using GCP for compute and S3 for storage, files generated by the task aren't automatically uploaded to S3. My SkyPilot version is 0.2.2.

Minimal example to reproduce the issue:
1. Create an AWS bucket, e.g. `skypilot-s3-bug`.
2. Launch the following task with `sky launch -c test-s3-bug s3_bug.yaml`. The contents of `s3_bug.yaml` are the following:
```yaml
resources:
  cloud: gcp

workdir: .

file_mounts:
  /data:
    name: skypilot-s3-bug
    mode: MOUNT

run: |
  echo "hello world" > /data/test.txt
```
4. After the task completes, the AWS bucket is empty.
5. Note that the file exists on the remote machine:
```
$ ssh test-s3-bug
$ cd /data/
$ ls
test.txt
$ cat test.txt 
hello world
```

A workaround is to manually sync to S3 by SSHing into the remote machine and running `aws s3 sync /data s3://skypilot-s3-bug`.
