### ISSUE TITLE
Python version mismatch when migrating from AWS to GCP

### ISSUE THREAD

**Issue by pschafhalter** [skypilot-org/skypilot#1604]
# Description of Problem
I recently migrated my workload from AWS to GCP and ran into issues with python versions. AWS's deep learning AMI is based on LTS versions of Ubuntu with Python 3.8+, whereas the default SkyPilot GCP image uses Debian 10 with Python 3.7. This resulted in an error as some libraries in my application relied on features from Python 3.8+. 

Note that the default SkyPilot image for AWS is based on Ubuntu 22.04 and uses Python 3.9.

I believe this is a SkyPilot issue because running workloads on any cloud requires a consistent environment. This can be addressed by launching SkyPilot tasks in images that are uniform across clouds with tools such as docker or the cloud's image marketplace.

# Current workaround
I've currently made some changes to my YAML files to set up and activate conda environments for the specific Python version I need:
```yaml
setup: |
  # Create an environment with Python 3.8.
  conda create -y -n my_task python=3.8
  source activate my_task
  # Install required Python packages.

run: |
  source activate experiments
  # Run the workload script.
```

Note that this workaround only addresses Python version mismatches. Version mismatches in other libraries and programs (e.g. `gcc`) will require a different solution. 

Posted at the request of @romilbhardwaj.
