### ISSUE TITLE
[Storage] Error message for Cloud URIs in source list is inaccurate

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1687]
When I am trying to launch a yaml below
```
file_mounts:
  /test:
    name: test-bucket-zhwu
    source: ['s3://test-bucket-zhwu', 'test.yaml']
    mode: COPY
```
The error message shows that `sky.exceptions.StorageSourceError: Local source path does not exist: s3://test-bucket-zhwu`. Do we want to instead hint to the user that the list should not include bucket instead? (Not urgent)

_Originally posted by @Michaelvll in https://github.com/skypilot-org/skypilot/pull/1677#pullrequestreview-1286179705_
