### ISSUE TITLE
Support supplying custom tags for AWS instances

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1696]
User requested a feature tagging all SkyPilot-launched AWS instances with their custom tags. 

They currently work around this by patching SkyPilot, adding the following to `sky/templates/aws-ray.yml.j2`:
```
      TagSpecifications:
        - ResourceType: instance
          Tags:
            - Key: skypilot-user
              Value: {{ user }}
            - Key: my-custom-tag
              Value: my-custom-value
```
User said
> although we have a temporary solution by patching, it’d be great if this can be officially supported
