### ISSUE TITLE
Support restricting search space to user-supplied list of `region`

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1912]
At least two users requested this feature:
1. User has data buckets replicated in certain regions, and would like unmanaged and managed spot jobs to only consider those regions
2. (Separate use case)  User knows they have quotas only in 2 regions, and would like to skip the lengthy failover as `sky` cycles through all regions in cheapest-cost order (this can be alleviated once we have quota-aware failover optimization)

Workaround today to restrict to certain regions:
```yaml
resources:
  cloud: aws
  image_id:
    us-west-1: skypilot:gpu-ubuntu-1804  # or 2004
    us-west-2: skypilot:gpu-ubuntu-1804  # or 2004
```

A proposed syntax
```
region: [us-east-1, us-west-2, …]
```
Needs some thought on how to handle when >1 cloud has the same region name. We can assume `cloud` is passed or raise an error if duplicates are detected.
