### ISSUE TITLE
gcs mount does not upload files from wandb folder

### ISSUE THREAD

**Issue by taomanwai** [skypilot-org/skypilot#1987]
Here is part of my sky.yaml

file_mounts:
  ~/sky_workdir/datasets/cifar10: ./datasets/cifar10
  ~/sky_workdir/wandb:
    name: skypilotbucket
    store: gcs
    mode: MOUNT  

Any comments?
Thanks in advance.

**Comment by romilbhardwaj** [comment]
Hi @taomanwai,

Thanks for the report. I tried replicating and can confirm that while the job is running, the wandb files are created in the bucket but they are all 0kb until the job completes. After the job completes, you should be able to access the files. Please let us know if this is not the case for you.

**Cause** - This behavior is observed because MOUNT mode employs a close-to-open consistency model (i.e., calling close() on a file will upload the entire file to the backing object store). Wandb keeps the file handles open till the python process terminates. Since the files are never closed during the run, they do not get written to GCS.

**Workaround** - If you'd like to stream these wandb files, you can consider running `cp <some_local_path>/wandb <mounted_path>` periodically in your script (perhaps at the end of every epoch). It should then get uploaded to GCS immediately at the end of the `cp` operation.

Here's the test script and YAML I used to replicate:
```python
# test.py

import wandb
import random # for demo script
import time

wandb.login()

epochs=10
lr=0.01

run = wandb.init(
    # Set the project where this run will be logged
    project="my-awesome-project",
    # Track hyperparameters and run metadata
    config={
        "learning_rate": lr,
        "epochs": epochs,
    })

offset = random.random() / 5
print(f"lr: {lr}")

# simulating a training run
for epoch in range(2, epochs):
    acc = 1 - 2 ** -epoch - random.random() / epoch - offset
    loss = 2 ** -epoch + random.random() / epoch + offset
    print(f"epoch={epoch}, accuracy={acc}, loss={loss}")
    wandb.log({"accuracy": acc, "loss": loss})
    time.sleep(60)
```

```yaml
resources:
  cloud: gcp

file_mounts:
  ~/sky_workdir/wandb:
    name: romilwandbtest
    store: gcs
    mode: MOUNT
  ~/.netrc: ~/.netrc  # To mount wandb credentials

workdir: .

setup: |
  pip install -q wandb

run: |
  python test.py
```
