### ISSUE TITLE
[Storage] Skip clouds that does not support storage when choosing default storage cloud

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2021]
The following lines use the task's cloud for the cloud used for the storage, but the cloud may not support the storage, e.g. `Lambda`/`Azure`/etc. We should failover to other enabled clouds.

https://github.com/skypilot-org/skypilot/blob/4849c866de987279081aafd6152c8f07f22c9918/sky/task.py#L670-L696

To reproduce:
```
resources:
  cloud: azure

file_mounts:
  /tmp:
    name: test-no-store-specified
    mode: MOUNT
```
cc @romilbhardwaj @landscapepainter
