### ISSUE TITLE
Support for multiple regions or zones

### ISSUE THREAD

**Issue by bilelomrani1** [skypilot-org/skypilot#2051]
When provisioning a new VM, is there a way to specify a list of regions or zones instead of a single region/zone? Perhaps using a list in the YAML config:
```yaml
resources:
  ...
  region:
    - us-east-1
    - us-east-2
    - ...
```
This would be a very nice addition to whitelist/blacklist some regions based on egress costs, price, latency, etc...
