### ISSUE TITLE
Sky storage downloads the folder from cloud storage to the path a level deeper

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#217]
The cloud storage will sync the folder to `~/test/test` on the remote instance if the `~/test` folder already exists with the following yaml.
```yaml
resources:
  cloud: was

storage:
- name: test
    source: /tmp/test

storage_mounts:
- storage: test
    mount_path: ~/test
```
