### ISSUE TITLE
[TPUVM] Job failed to be submitted to TPUVM

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2227]
To reproduce:
```
resources:
  cloud: gcp
  accelerators: tpu-v3-8
  accelerator_args:
    runtime_version: tpu-vm-base
    tpu_vm: True
  use_spot: True

run: |
  echo "Hello World"
```

The reason is that the tpu vm has python 3.11, which causes the underlying ray job fails due to https://github.com/ray-project/ray/commit/ee64dbc03d6b21dcfefb893150ee5c7f1ebb705e
