### ISSUE TITLE
Add support for Lambda Cloud Storage

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2231]
https://lambdalabs.com/blog/persistent-storage-beta

This will be useful for serving use-case. Data will be read multiple times and needs high IOPS + bandwidth.

**Comment by rdabane** [comment]
I'm also looking for this feature.

**Comment by romilbhardwaj** [comment]
Thanks for your interest @rdabane! Can you share your use-case/workload (e.g., reading datasets for training, writing model checkpoints, etc.) so we can plan this feature better?

**Comment by rdabane** [comment]
@romilbhardwaj 
As of today we can get access to cheap H100 gpu's at lambda only. 
My use case is order of TB data to be stored in lambda's persistence storage, spin up the v100/h100 gpu cluster for faster training iterations with checkpoints being stored ( to be later downloaded to my machine based on the performance ). 
Right now I've spin up a gpu on the lambda cloud. Copy from s3/gcp to the local disk. Then start training/checkpointing.

The primary issue I see with lambda is that sometimes their persistence storage is not colocated with their gpu cluster. ( Utah/Plano ?) 

Again thanks for the work. Would love to help on this feature.
Please let me know what I could do to accelerate this feature .

**Comment by romilbhardwaj** [comment]
Thanks for the description @rdabane! This is interesting and we'd love to have support for this? We're very open to code contributions - would be willing to add support for lambda persistent storage? :)

At a high level, I see this working like:

```yaml
resources:
  cloud: lambda
  accelerators: H100:1

file_mounts:
  /home/ubuntu/my-existing-lambda-storage:  # This path is fixed, lambda API doesn't allow custom mount points 
    name: my-existing-lambda-storage  # Must be pre-existing, since lambda API doesn't support creation
    store: lambda  # New store type added to Sky Storage
    mode: MOUNT  # Only mount mode is allowed for lambda

run:
  python train.py --dataset /mydataset/
```

When we run sky launch, we add the user specified persistent storage to the `filesystems` arg in [our call](https://github.com/skypilot-org/skypilot/blob/f5526d43b49f5e8bf184f73c58193d9d203cdc1e/sky/skylet/providers/lambda_cloud/node_provider.py#L275-L280) to lambda's [launch API](https://cloud.lambdalabs.com/api/v1/docs#operation/launchInstance). What do you think?
