### ISSUE TITLE
[Storage]Paths with empty space character failing in task yaml

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#2243]
A user reported a failing case of task yaml regards to paths with empty spaces included for `file_mounts`. And this is due to `aws s3 sync` or `gsutil rsync` failing to run with the paths including empty spaces. We need to fix this case so that the following case successfully runs:

```
file_mounts:
  /my_mnt:
    name: my-storage
    source: ~/my test
    store: s3 #(for gcs,r2 as well)
```
