### ISSUE TITLE
TPU: `down --purge` failed to purge a non-launched TPU pod in invalid zone

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2269]
Tried provisioning a TPU pod in `us-east1-d`:
```
resources:
  cloud: gcp
  region: us-east1
  zone: us-east1-d
  use_spot: true

  accelerators: tpu-v3-128
  accelerator_args:
    runtime_version: tpu-vm-base
    tpu_vm: true
```
This failed with
```
I 07-18 20:57:31 cloud_vm_ray_backend.py:1704] Launching on GCP us-east1 (us-east1-d)
I 07-18 20:57:46 cloud_vm_ray_backend.py:733] Got googleapiclient.errors.HttpError: <HttpError 403 when requesting https://tpu.googleapis.com/v2alpha1/projects/1234567/locations/us-east1-d/nodes?nodeId=ray-sky-xxxxxxx-head-xxxxxx-tpu&alt=json returned "Location us-east1-d is not found or access is unauthorized.". Details: "Location us-east1-d is not found or access is unauthorized.">
```
which is expected.

However,
```
» sky down sky-136e-zongheng    -p
Terminating 1 cluster: sky-136e-zongheng. Proceed? [Y/n]:
sky.exceptions.ClusterStatusFetchingError: Failed to query GCP cluster 'sky-136e-zongheng' status: WARNING:  Python 3.5-3.7 will be deprecated on August 8th, 2023. Please use Python version 3.8 and up.

If you have a compatible Python interpreter installed, you can use it by setting
the CLOUDSDK_PYTHON environment variable to point to it.

ERROR: (gcloud.compute.tpus.tpu-vm.list) PERMISSION_DENIED: Location us-east1-d is not found or access is unauthorized.
```
which is unexpected -- `--purge` should bypass this. At this point, no node was launched and this cluster is stuck in my cluster table requiring manual cleanup.
