### ISSUE TITLE
Failed to find the directory specified in storage_mounts on remote VM

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#228]
I specified the below `storage_mounts` in the yaml file and re-run `sky launch`.
But sky did not download the directory `~/dataset2` from cloud storage to the remote VM.
```
storage:
  - name: my-gnn-dataset
    source: /data/weichiang/dataset
    #force_stores: [s3] # Could be [s3, gcs], [gcs] default: None
    persistent: True

storage_mounts:
  - storage: my-gnn-dataset
    mount_path: ~/dataset2
```

```
ubuntu@ip-172-31-14-71:~$ ls
LICENSE  Nvidia_Cloud_EULA.pdf  README  anaconda3  dataset  examples  ray_bootstrap_config.yaml  ray_bootstrap_key.pem  sky_logs  sky_workdir  src  tools  tutorials
```
I'm based on the latest commit https://github.com/concretevitamin/sky-experiments/commit/135514417abcf48c553bdc9a22cefccc2b024c48
@michaelzhiluo is this a bug?
