### ISSUE TITLE
[Core] sky launch slowdown when GCP image id specified

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#2405]
I notice some slow down on `sky launch` when specifying `image_id` for GCP. It took 25s til the y/n prompt, compared to 3s without image_id. 

```YAML
resources:
  accelerators: A100:1
  cloud: gcp
  image_id: projects/skypilot-375900/global/images/coder
```
According to @Michaelvll @cblmemo , this may be related to the per-zone optimization + GCP API query latency https://github.com/skypilot-org/skypilot/blob/5cf04eb20d3313ef93521776ddc7eae36303a3e8/sky/resources.py#L746
We can try to improve the performance.
