### ISSUE TITLE
[Docs]  gcp image_id example on page /reference/yaml-spec.html not working

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#2409]
The following example provided for gcp is currently not working.
`# image_id: projects/deeplearning-platform-release/global/images/family/tf2-ent-2-1-cpu-ubuntu-2004`

ubuntu.yaml:
```
resources:
    cloud: gcp
    image_id: projects/deeplearning-platform-release/global/images/family/tf2-ent-2-1-cpu-ubuntu-2004
    instance_type: n2-standard-8
```

Repro.:
Running `sky launch ubuntu.yaml --cloud gcp -y` on the following task yaml would raise `ValueError`:
`ValueError: Image 'projects/deeplearning-platform-release/global/images/family/tf2-ent-2-1-cpu-ubuntu-2004' not found in GCP.`
