### ISSUE TITLE
Skypilot still attempts to connect to all cloud even when explicitly given one particular cloud provider

### ISSUE THREAD

**Issue by htahir1** [skypilot-org/skypilot#2414]
Given a simple task YAML that aims to launch a simple VM in GCP like:

```yaml
resources:
  cloud: gcp

# Main program (optional, but recommended) to run on every node of the cluster.
run: |
  echo "hi"
  ```
  
  Skypilot still attempts to look at AWS credentials like so:
  
  ```
  I 08-17 18:29:49 aws_catalog.py:78] Fetching availability zones mapping for AWS...
RuntimeError: Failed to retrieve AWS regions. Please ensure that the `ec2:DescribeRegions` action is enabled for your AWS account in IAM. Ref: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRegions.html
```

However, expected behavior is that given an explicit cloud, it should only look at that cloud.
