### ISSUE TITLE
[Storage][k8s_cloud_beta1-minio] Possible "Transport endpoint is not connected".

### ISSUE THREAD

**Issue by aviweit** [skypilot-org/skypilot#2436]
I installed SkyPilot from https://github.com/aviweit/skypilot/tree/k8s_cloud_beta1-minio
and launched the below task.yaml:

```
num_nodes: 1

resources:
  memory: 2
  cpus: 1
  cloud: kubernetes

file_mounts:

  /dataset-demo:
    # sky-demo-dataset bucket mounted under /dataset-demo folder
    # in ray cluster
    source: minio://sky-demo-dataset
    mode: MOUNT

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  echo "Hello, how are you?"
  conda env list

  # ensure sky/data contents are listed
  ls -l /dataset-demo
  # Write to bucket in MOUNT mode should pass
  echo "hello" > /dataset-demo/hello.txt
```

`sky launch -c test task.yaml`

The task succeeded. I verified that `sky-demo-dataset` inside MinIO was correctly set with `hello.txt` object.

I wanted to further test the mount point so I logged into the ray cluster via `ssh test`

Invoked mount to ensure S3 mount point exists: `$ mount | grep sky-demo-dataset`
I could list /dataset-demo and see the object. I could also create additional object files and folders via similar commands to `echo "foo" > /dataset-demo/file_name.txt` and `mkdir /dataset-demo/myfolder` respectively.

However, when I tried the append operation, I got `Operation not supported` and then the mount point stopped to work (I got `Transport endpoint is not connected`) on every file operation:

```
(base) sky@test-ray-head:~$ echo test >> /dataset-demo/hello.txt
-bash: echo: write error: Operation not supported
(base) sky@test-ray-head:~$ cat /dataset-demo/hello.txt
cat: /dataset-demo/hello.txt: Transport endpoint is not connected
```
