### ISSUE TITLE
[config] Pre-checks for `~/.sky/config.yaml`

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2474]
Currently, we don't have a way to pre-check the `~/.sky/config.yaml`, making it very easy to miss spell or setting wrong configs in the yaml. We can apply the json schema check to the `~/.sky/config.yaml` to make sure there is no unexpected settings.

A user met the issue when specifying the spot controller's resources requirement, but missing one section (`resources`):
```
spot:
  controller:
    cloud: gcp
    region: us-west1
```
