### ISSUE TITLE
`sky launch --gpu=T4:4 launch.yaml` will ignore the cloud in yaml 

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#249]
```yaml
# launch.yaml
resources:
  cloud: aws
  accelerators:
    V100: 4
```
`sky launch --gpu=T4:4 launch.yaml` will not directly run on aws but try gcp first.
