### ISSUE TITLE
[Storage][k8s] Support mounting data sources on Kubernetes cluster

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2497]
K8s users often have data locally stored on the cluster, typically in the form of a persistent volume + pvc, or a NFS mounted to all nodes, accessed via a hostpath. 

From a user:
```
We have to use the hostpath instead because we cannot transfer the whole datasets directory to the pvc. I want the option to add the pvc or hostpath to the task.yaml.
```

Our k8s features needs to add support for attaching and accessing data on persistent volumes, hostpaths and/or any other mechanism used by users to access their local data.

**Comment by romilbhardwaj** [comment]
We now have a temporary workaround for this.

Users can edit `~/.sky/config.yaml` to specify custom volumes and volume mounts to attach to their pods ([docs](https://skypilot.readthedocs.io/en/latest/reference/config.html)):
```
  pod_config:
    spec:
      containers:
        - volumeMounts:       # Custom volume mounts for the pod
            - mountPath: /foo
              name: example-volume
              readOnly: true
      volumes:
        - name: example-volume
          hostPath:
            path: /tmp
            type: Directory
```

Note that is not an ideal solution since `config.yaml` would apply globally to all pods, and selecting volume mounts on a per-pod basis is not possible through this mechanism.
