### ISSUE TITLE
[Spot] Failed to catch user file mounts error which causes the retry forever

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2503]
Observed by @infwinston and a user, that if a file mounts error happens, the spot job will not become `FAILED`, but instead retry forever.

To reproduce:
1. `sky spot launch -n test-fm test.yaml`
2. terminate the spot cluster

```
# test.yaml

file_mounts:
  /data:
    source: gs://existing-bucket/non-exist-folder
    mode: copy
```

The spot job will keep retrying forever, as we did not catch the storage error.
To fix the issue, we can catch the storage exceptions in the following place and raise `ProvisionPrechecksError` to avoid retrying:
https://github.com/skypilot-org/skypilot/blob/3213d3a14ecd86c3022f071e671fcf62c5ca48ba/sky/spot/recovery_strategy.py#L331-L336
