### ISSUE TITLE
[Storage] Precheck the existence of file mounts.

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2505]
The following command will go ahead to launch the cluster, but fail after the cluster is launched. We should check the existence of the source in filemounts, before launching the cluster:

```
# test.yaml
file_mounts:
  /data:
    source: gs://existing-bucket/non-existing-folder
    mode: COPY
```
