### ISSUE TITLE
Cuda not working via skypilot (works on direct instance)

### ISSUE THREAD

**Issue by stin7** [skypilot-org/skypilot#2510]
Here's some minimal code to repro:

cuda.py
``` python
import torch

print(f"torch.cuda.is_available(): {torch.cuda.is_available()}")
print(f"torch.cuda.device_count(): {torch.cuda.device_count()}")
print(f"torch.cuda.current_device(): {torch.cuda.current_device()}")
print(f"torch.cuda.device(0): {torch.cuda.device(0)}")
print(f"torch.cuda.get_device_name(0): {torch.cuda.get_device_name(0)}")
```

hello_sky.yaml:
``` yaml
# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: .

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."
  pip3 install torch

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  echo "Hello, SkyPilot!"
  conda env list
  python cuda.py
```

Running `sky launch -c mycluster hello_sky.yaml` results in this output:

``` bash
(task, pid=201122) Hello, SkyPilot!
(task, pid=201122) # conda environments:
(task, pid=201122) #
(task, pid=201122) base                  *  /home/ubuntu/miniconda3
(task, pid=201122) 
(task, pid=201122) torch.cuda.is_available(): False
(task, pid=201122) torch.cuda.device_count(): 0
(task, pid=201122) Traceback (most recent call last):
(task, pid=201122)   File "/home/ubuntu/sky_workdir/cuda.py", line 5, in <module>
(task, pid=201122)     print(f"torch.cuda.current_device(): {torch.cuda.current_device()}")
(task, pid=201122)   File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
(task, pid=201122)     _lazy_init()
(task, pid=201122)   File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
(task, pid=201122)     torch._C._cuda_init()
(task, pid=201122) RuntimeError: No CUDA GPUs are available

ERROR: Job 4 failed with return code list: [1]
INFO: Job finished (status: FAILED).
Shared connection to 129.153.155.195 closed.
I 09-04 14:34:32 cloud_vm_ray_backend.py:3258] Job ID: 4
I 09-04 14:34:32 cloud_vm_ray_backend.py:3258] To cancel the job:       sky cancel mycluster 4
I 09-04 14:34:32 cloud_vm_ray_backend.py:3258] To stream job logs:      sky logs mycluster 4
I 09-04 14:34:32 cloud_vm_ray_backend.py:3258] To view the job queue:   sky queue mycluster
I 09-04 14:34:32 cloud_vm_ray_backend.py:3381] 
I 09-04 14:34:32 cloud_vm_ray_backend.py:3381] Cluster name: mycluster
I 09-04 14:34:32 cloud_vm_ray_backend.py:3381] To log into the head VM: ssh mycluster
I 09-04 14:34:32 cloud_vm_ray_backend.py:3381] To submit a job:         sky exec mycluster yaml_file
I 09-04 14:34:32 cloud_vm_ray_backend.py:3381] To stop the cluster:     sky stop mycluster
I 09-04 14:34:32 cloud_vm_ray_backend.py:3381] To teardown the cluster: sky down mycluster
Clusters
NAME       LAUNCHED     RESOURCES                          STATUS  AUTOSTOP  COMMAND                       
mycluster  17 secs ago  1x Lambda(gpu_1x_a10, {'A10': 1})  UP      -         sky launch -c mycluster h... 
```

As you can see, the cluster clearly has an A10 GPU.
Just to be sure, I opened the instance in Lambda directly, and opened a notebook to run the same code, which successfully detects the GPU.

Input
``` python
import torch

print(f"torch.cuda.is_available(): {torch.cuda.is_available()}")
print(f"torch.cuda.device_count(): {torch.cuda.device_count()}")
print(f"torch.cuda.current_device(): {torch.cuda.current_device()}")
print(f"torch.cuda.device(0): {torch.cuda.device(0)}")
print(f"torch.cuda.get_device_name(0): {torch.cuda.get_device_name(0)}")
```

Output
``` text
torch.cuda.is_available(): True
torch.cuda.device_count(): 1
torch.cuda.current_device(): 0
torch.cuda.device(0): <torch.cuda.device object at 0x7f50bc68a6d0>
torch.cuda.get_device_name(0): NVIDIA A10
```

Am I missing some configuration settings in my yaml to ensure skypilot has access to the GPUs?
