### ISSUE TITLE
[Provisioner] Support docker image with multiple region image_id

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#2575]
The current implementation of the docker image only supports a single region, i.e.
```yaml
resources:
  image_id: docker:ubuntu
```
As discussed in #2574, we could allow multiple regions with docker image, even mixture of docker image and normal image:
```yaml
resources:
  image_id:
    us-east-1: ami-xxx
    us-west-1: docker:ubuntu
```
