### ISSUE TITLE
UX: confusing ValueError: Cannot specify spot_recovery without use_spot set to True.

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2591]
```
» sky spot launch test.yaml
Task from YAML spec: test.yaml
ValueError: Cannot specify spot_recovery without use_spot set to True.
```

```
» cat test.yaml                                                                 
resources:
  cpus: 8
  use_spot: false
```

Reasons it's confusing
- `spot_recovery` is a very hidden / advanced field and should not be surfaced
- With the `spot launch` intent, I think we should allow the above YAML by overriding the `use_spot` field ourselves, and perhaps print a hint message on the override
