### ISSUE TITLE
Skypilot ignores spot controller specifications

### ISSUE THREAD

**Issue by DavidePaglieri** [skypilot-org/skypilot#2600]
I've been try to create a low-budget spot controller, the standard one that I get assigned in gcp is an instance of `n2-standard-8`, costing 0.39$ per hour. What I want to send are small batches of spot jobs with T4 GPUs, costing 0.13$ per hour each. 

It seems like I can't make skypilot create a cheaper controller `n2-standard-4` or even `n2-standard-2`. I modify the `~/.sky/config.yaml` file in the following way:

```
spot:
    controller:
        resources:
        cloud: gcp
        instance_type: n2-standard-4
        cpus: 4
        disk_size: 50
```

However this doesn't work and skypilot will still create a `n2-standard-8` instance. Can you please help?

**Comment by concretevitamin** [comment]
Hi @DavidePaglieri! Can you try this indented version?
```
spot:
    controller:
        resources:
            cloud: gcp
            instance_type: n2-standard-4
            cpus: 4
            disk_size: 50
```
Also, what's the version you are using, `sky -v`?
