### ISSUE TITLE
[UX] Confusing error message when ssh proxy command is set for one region but trying to launch on another

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2607]
When the `~/.sky/config.yaml` contains the following setting:
```
aws:
  vpc_name: skypilot-test-vpc
  use_internal_ips: true
  ssh_proxy_command:
    us-east-1: ssh -W %h:%p -p 22 -o StrictHostKeyChecking=no ec2-user@<IP> -i ~/.ssh/sky-key
```

And when trying to launch a cluster on another region, the following error shows up without any hints for the reason of the proxy command:
```
$ sky launch --cloud aws --cpus 2 --region us-east-2  
W 09-25 12:21:10 resources.py:587] Request AWS(m6i.large) cannot be satisfied by any feasible region. To fix, check that ssh_proxy_command's region keys include the regions to use.
I 09-25 12:21:10 optimizer.py:1045] No resource satisfying AWS(cpus=2) on AWS.
I 09-25 12:21:10 optimizer.py:1054] Try specifying a different CPU count, or add "+" to the end of the CPU count to allow for larger instances.
sky.exceptions.ResourcesUnavailableError: Catalog does not contain any instances satisfying the request:
Task(run=<empty>)
  resources: AWS(cpus=2). Region: us-east-2.

To fix: relax or change the resource requirements.

Hint: sky show-gpus to list available accelerators.
      sky check to check the enabled clouds.
```
