### ISSUE TITLE
`sky launch` task with fewer num_nodes on existing cluster scales down the cluster

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#270]
`sky launch -c test launch.yaml` creates 4 nodes, but if we do `sky launch -c test task.yaml`, the cluster will be scaled down to 1 node. That may not be the expected behavior, since the user may only want to run the setup on the 4-node cluster. 

Proposed behavior: when launching a task with fewer num_nodes on an existing cluster, do not scale the cluster.

The two solutions I could think of all require API change:
1. Include the num_nodes in the `sky.Resources()`, so that the provision function can use the `num_nodes` in the `to_provision` to launch the cluster, rather than using the one in the task.
2. Let the provision function take the `num_nodes` argument.

```yaml
# launch.yaml
resources:
  cloud: aws
  accelerators:
    V100: 1
num_nodes: 4
```

```yaml
# task.yaml
resources:
  cloud: aws
  accelerators:
    V100: 0.5
num_nodes: 1

setup: # task specific setup
```
