### ISSUE TITLE
YAML: `any_of`/`ordered` should inherit base resources config

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2831]
Also, this task yaml will make it quite complicated to also select some accelerators, as we have to add the same accelerator for all the items in `any_of`. In the future, we should be able to take default fields and additional `any_of`, i.e.:
```yaml
resources:
  accelerators: V100
  any_of:
      # AWS:
      - region: eu-central-1
      - region: eu-west-1
      - region: eu-west-2
      - region: eu-west-3
      - region: eu-north-1
      ...
```

_Originally posted by @Michaelvll in https://github.com/skypilot-org/skypilot/pull/2827#discussion_r1409911431_
