### ISSUE TITLE
GCP VPC YAML setting is not supported.

### ISSUE THREAD

**Issue by saihtaungkham** [skypilot-org/skypilot#2842]
I have instructed Skypilot to use the defined VPC setting in our project in the Google Cloud Platform. However, launching the `sky check` command triggered the following unexpected error.

```
ValueError: Invalid config YAML (/Users/<user_name>/.sky/config.yaml): The following fields are invalid:
Found unsupported field 'vpc_name'.
Found unsupported field 'use_internal_ips'.
Found unsupported field 'ssh_proxy_command'.
```

Here is my `config.yaml` setting:

```
gcp:
  vpc_name: experiment-vpc
  use_internal_ips: true
  ssh_proxy_command: /usr/bin/ssh ...
```

SkyPilot Version : `skypilot, version 0.4.1`

Is there anything that I have missed? Thanks.
