### ISSUE TITLE
Issues with AWS inferentia: Disk is not mounted, reusage of existing venv, job keeps queueing.

### ISSUE THREAD

**Issue by michaelfeil** [skypilot-org/skypilot#2967]
Here is my sky setup, using `0.4.1` and `awscliv2` to submit. CC @mmcclean-aws & Team at Annapurna

```yaml
...

resources:
  cloud: aws
  # AWS inferentia, including neuronx
  # https://github.com/skypilot-org/skypilot/issues/2686#issuecomment-1754067953
  instance_type: inf2.8xlarge
  # get pytorch image
  #      aws ec2 describe-images --region us-west-2 --owners amazon --filters 'Name=name,Values=Deep Learning AMI Neuron PyTorch *' 'Name=state,Values=available' --query 'reverse(sort_by(Images, &CreationDate))'

  image_id: ami-0a1063844e84bee6a
  # region: us-east-1 # ami-0c43538b49cfc5642 is the image for east-1
  region: us-west-2 # ami-0a1063844e84bee6a is the image for west-2

  disk_size: 1024
```
## Issues: 
Background: I am trying to get this example running. I uesed the plain `neuron 2.15.9 + torch` `ami` image.
https://github.com/aws-neuron/aws-neuron-samples/blob/4777b96bc32639242009bd5ecdea0a718a272348/torch-neuronx/transformers-neuronx/inference/meta-llama-2-13b-sampling.ipynb

I got the model `TinyLLama-1.1B` running with the example. 💯  For more productive usage, we encountered some issues. Especially, when loading models > 10GB:

# Issue 1: Disk is not mounted. **(Solved)**
The root disk of the default requested instance is 35gb. If I request `disk_size: 1024`, this disk is not mounted, aka. `df -h` just shows 35gb, the other 1024 are missing. This resulted in issues with any `llama-7B`+ sizes.

#### Solution:
  https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Images:visibility=public-images;search=:huggingface-neuron;v=3;$case=tags:false%5C,client:false;$regex=tags:false%5C,client:false

  hf-images did a better job.
```
  image_id: ami-04dd1be93bedbc674 # us-west-2
  region: us-west-2
```

# Issue 2: Conflicting environments when installing into `aws_neuron_venv_pytorch` **(solved with hf-image)**

The dependencies on AWS inferentia are somehow not straigtforward, hence the `ami-` image. I noticed that there is issues with `PermissionError` when installing in the existing env. Beyond, there are issue with parallen jobs that are queued, going through the `setup: |` stage. 
Also there are double activated envs, ` (base) (aws_neuron_venv_pytorch) michael@machine`, quite confusing.

```bash
# part of setup: |
conda deactivate
# free permission issues when 
sudo chmod -R 777 /opt/aws_neuron_venv_pytorch/*
source /opt/aws_neuron_venv_pytorch/bin/activate
pip install transformers-neuronx sentencepiece
```

Any suggestions would be welcome.

**Comment by concretevitamin** [comment]
> # Issue 1: Disk is not mounted.
> The root disk of the default requested instance is 35gb. If I request `disk_size: 1024`, this disk is not mounted, aka. `df -h` just shows 35gb, the other 1024 are missing. This resulted in issues with any `llama-7B`+ sizes.

Thanks for the report @michaelfeil.

I can reproduce this issue on the main branch 1e53317b5. The 1T disk is provisioned but not as root disk:
```
$ lsblk
NAME          MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1       259:0    0  35G  0 disk
├─nvme0n1p1   259:2    0  35G  0 part /
└─nvme0n1p128 259:3    0   1M  0 part
nvme1n1       259:1    0   1T  0 disk
```
It can also be seen on console:

<img width="889" alt="Screen Shot 2024-01-09 at 15 46 07" src="https://github.com/skypilot-org/skypilot/assets/592670/db6b32e5-7e24-428e-820e-b163f25eb82b">

**Comment by concretevitamin** [comment]
@michaelfeil Another workaround is to replace

https://github.com/skypilot-org/skypilot/blob/v0.4.1/sky/templates/aws-ray.yml.j2#L76

with `/dev/xvda`.

It appears this is a quirkiness of this particular inferentia AMI. Another inferentia AMI  

https://github.com/skypilot-org/skypilot/issues/2686#issuecomment-1754067953

works out of the box with `/dev/sda1/`. cc @Michaelvll

**Comment by michaelfeil** [comment]
@concretevitamin Thanks for the reproduction, this is exactly what I am seeing.

For future reference, the following helped me to mount the disk.
```bash
# neuron_attach_disk.sh
disk_mount_path=/mnt/neuron
device=/dev/sda1
# Mount the disk if it is not already mounted
if ! mountpoint -q $disk_mount_path; then
    sudo mkdir -p $disk_mount_path
    # Format the disk, create a file system 
    sudo mkfs -t xfs /dev/sda1
    # mount the disk
    sudo mount $device $disk_mount_path
    # adjust user permissions
    sudo chown -R $USER:$USER $disk_mount_path
fi
```

# Issue 3: Job just reaches `setup` stage, never makes it into `run`

The job is stuck forever in `INFO: Waiting for task resources on 1 node. This will block if the cluster is full.`.

I submit a single job to a new cluster: `sky launch -c sky-inf-rep ./sky_reproduce.yaml `


<details>
  <summary>Here is the ` ./sky_reproduce.yaml` </summary>
   
  ```yaml
  name: demo-inf2-issues

  resources:
    cloud: aws
    # AWS inferentia, including neuronx
    # https://github.com/skypilot-org/skypilot/issues/2686#issuecomment-1754067953
    instance_type: inf2.8xlarge
    # get pytorch image
    #      aws ec2 describe-images --region us-west-2 --owners amazon --filters 'Name=name,Values=Deep Learning AMI Neuron PyTorch *' 'Name=state,Values=available' --query 'reverse(sort_by(Images, &CreationDate))'

    image_id: ami-0a1063844e84bee6a
    # region: us-east-1 # ami-0c43538b49cfc5642 is the image for east-1
    region: us-west-2 # ami-0a1063844e84bee6a is the image for west-2

    disk_size: 1024

  workdir: .

  setup: |
    echo "Starting setup."
    # possible mount disk here and activate env
    python -m pip install numpy

  run: |
    echo "Starting run."
    # activate env
    python -m pip install pandas
  ```
</details>

<details>
  <summary>Output `INFO: Waiting for task resources on 1 node. This will block if the cluster is full.`</summary>
  
  ```
  launch -c sky-inf-rep ./sky_reproduce.yaml 
  Task from YAML spec: ./sky_reproduce.yaml
  I 01-10 12:22:33 optimizer.py:674] == Optimizer ==
  I 01-10 12:22:33 optimizer.py:697] Estimated cost: $2.0 / hour
  I 01-10 12:22:33 optimizer.py:697] 
  I 01-10 12:22:33 optimizer.py:769] Considered resources (1 node):
  I 01-10 12:22:33 optimizer.py:818] -------------------------------------------------------------------------------------------
  I 01-10 12:22:33 optimizer.py:818]  CLOUD   INSTANCE       vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
  I 01-10 12:22:33 optimizer.py:818] -------------------------------------------------------------------------------------------
  I 01-10 12:22:33 optimizer.py:818]  AWS     inf2.8xlarge   32      128       Inferentia:1   us-west-2     1.97          ✔     
  I 01-10 12:22:33 optimizer.py:818] -------------------------------------------------------------------------------------------
  I 01-10 12:22:33 optimizer.py:818] 
  Launching a new cluster 'sky-inf-rep'. Proceed? [Y/n]: Y
  I 01-10 12:24:06 cloud_vm_ray_backend.py:4380] Creating a new cluster: 'sky-inf-rep' [1x AWS(inf2.8xlarge, {'Inferentia': 1}, image_id={'us-west-2': 'ami-0a1063844e84bee6a'}, disk_size=1024)].
  I 01-10 12:24:06 cloud_vm_ray_backend.py:4380] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
  I 01-10 12:24:07 cloud_vm_ray_backend.py:1449] To view detailed progress: tail -n100 -f /home/michi/sky_logs/sky-2024-01-10-12-22-31-311291/provision.log
  I 01-10 12:24:08 provisioner.py:72] Launching on AWS us-west-2 (us-west-2a,us-west-2b,us-west-2c,us-west-2d)
  I 01-10 12:24:52 provisioner.py:358] Successfully provisioned or found existing instance.
  I 01-10 12:26:18 provisioner.py:452] Successfully provisioned cluster: sky-inf-rep
  I 01-10 12:26:19 cloud_vm_ray_backend.py:3145] Syncing workdir (to 1 node): . -> ~/sky_workdir
  I 01-10 12:26:19 cloud_vm_ray_backend.py:3153] To view detailed progress: tail -n100 -f ~/sky_logs/sky-2024-01-10-12-22-31-311291/workdir_sync.log
  I 01-10 12:26:20 cloud_vm_ray_backend.py:3249] Running setup on 1 node.
  Warning: Permanently added '35.87.20.79' (ED25519) to the list of known hosts.
  I 01-10 12:26:28 cloud_vm_ray_backend.py:3259] Setup completed.
  I 01-10 12:26:33 cloud_vm_ray_backend.py:3356] Job submitted with Job ID: 1
  I 01-10 11:26:33 log_lib.py:431] Start streaming logs for job 1.
  INFO: Tip: use Ctrl-C to exit log streaming (task will not be killed).
  INFO: Waiting for task resources on 1 node. This will block if the cluster is full.

  # @michaelfeil note: hangs for min 15minutes here. 
  ```
