### ISSUE TITLE
Docker images not working when using serve up

### ISSUE THREAD

**Issue by benbot** [skypilot-org/skypilot#2982]
When trying to use `sky serve up` with a config like this which uses a custom docker image

```
resources:
  image_id: docker:imagename:dev
  accelerators: {L4:1}
  ports: 5000
  disk_size: 100

envs:
  SKYPILOT_DOCKER_USERNAME: username
  SKYPILOT_DOCKER_PASSWORD: password
  SKYPILOT_DOCKER_SERVER: docker.registry.server

...
```

I get this error

```
Service Spec:
Readiness probe method:           GET /check
Readiness initial delay seconds:  1200
Replica autoscaling policy:       Autoscaling from 0 to 4 replicas        
Each replica will use the following resources (estimated):
I 01-13 21:14:09 optimizer.py:694] == Optimizer ==
I 01-13 21:14:09 optimizer.py:705] Target: minimizing cost
I 01-13 21:14:09 optimizer.py:717] Estimated cost: $0.7 / hour
I 01-13 21:14:09 optimizer.py:717] 
TypeError: Object of type DockerLoginConfig is not JSON serializable
```
