### ISSUE TITLE
Sky Serve not working for me anymore - timeout

### ISSUE THREAD

**Issue by manishiitg** [skypilot-org/skypilot#2999]
i am deploying a vLLM serve using the config

```
resources:
  ports: 8000
  accelerators: L4:1
  use_spot: True
  cloud: gcp
  cpus: 2+
  disk_size: 128

service:
  readiness_probe: 
    path: /health
  replica_policy:
    min_replicas: 1
  
setup: |
  

run: |

  docker run --gpus all \
   -p 8000:8000  \
   --shm-size=12gb \
   vllm/vllm-openai \
   --model manishiitg/open-aditi-hi-v1-dpo-merged --dtype float16 --max-model-len 4096 \
   -tp 1


```

curl -L http://35.222.87.103:30001/v1/models

on the controller ip gives me request timeout 

but doing it on the server ip works

```
curl 34.16.35.86:8000/v1/models

{"object":"list","data":[{"id":"manishiitg/open-aditi-hi-v1-dpo-merged","object":"model","created":1705635002,"owned_by":"vllm","root":"manishiitg/open-aditi-hi-v1-dpo-merged","parent":null,"permission":[{"id":"modelperm-0343f551b0b448abbd5dbd2eb122dd94","object":"model_permission","created":1705635002,"allow_create_engine":false,"allow_sampling":true,"allow_logprobs":true,"allow_search_indices":false,"allow_view":true,"allow_fine_tuning":false,"organization":"*","group":null,"is_blocking":false}]}]}
```
