### ISSUE TITLE
[Serve] Support env var in `service` field

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3048]
When creating an example for serving llm, it will be much easier if the service field can support the following:

```yaml
service:
  readiness_probe:
    path: /v1/chat/completions
    post_data:
      model: $MODEL_NAME
      messages:
        - role: user
          content: How to print hello world?

envs:
  MODEL_NAME: codellama/CodeLlama-70b-Python-hf

run: |
  python -u -m vllm.entrypoints.openai.api_server \
                --host 0.0.0.0 \
                --model $MODEL_NAME \
                --tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE | tee ~/openai_api_server.log
```
cc'ing @cblmemo @MaoZiming
