### ISSUE TITLE
Ability to specify the min / max number of resources for a given type.

### ISSUE THREAD

**Issue by JGSweets** [skypilot-org/skypilot#3099]
It would be great if in addition to `ordered`, `any_of`, we could specify the min / max count for each resource specification? 
e.g. max - 2 A10g: 4, max - 1 A100: 8 etc.

My original thoughts were this would make sense to go inline with the specified desired resources, but I could also see this being part of the replication policy or a separation section under resources as well which specifies cluster requirements.

If under resources when specifying types, possibly like:
```yaml
resources:
  ordered: # Candidate resources in a preference order
    - cloud: gcp
      accelerators:  {A100-80GB:8, A100-40GB:8}
      cluster_requirements:
        "A100-80GB:8":
          count: 1  # as opposed to min / max, this requires the count to be 1
        "A100-40GB:8":
          min: 0
          max: 2        
    - instance_type: g5.xlarge
      cluster_requirements:
        g5.xlarge:
          min: 4  # not specifying a max allows it to scale above 4
    - cloud: azure
      region: eastus
      accelerator: A100
      cluster_requirements:
        A100:
          max: 3  # not specifying a min allows it to scale to 0
```
This would clearly require validation between the replica policy allowance and specification of cluster requirements.
However, maybe the replica policy should should specify how to determine vs how many? Or maybe it is good to have an overall in the replica policy as it forces an overall summary which may not be as clear if giving a `cluster_requirements` field. Thoughts?
