### ISSUE TITLE
[Feature Request] Ordered and Any_of should also work for only partial settings

### ISSUE THREAD

**Issue by manzke** [skypilot-org/skypilot#3106]
Right now we have to duplicate all keys to make it working with any_of or ordered.

Example:
```
ordered: 
    - region: eu-central-1
      accelerators: A10G:1
      memory: 24+
    - region: eu-central-1
      accelerators: T4:4
      memory: 24+
    - region: eu-west-1
      accelerators: A10G:1
      memory: 24+
    - region: eu-west-2
      accelerators: A10G:1
      memory: 24+
    - region: eu-west-3
      accelerators: A10G:1
      memory: 24+
    - region: eu-north-1
      accelerators: A10G:1
      memory: 24+
    - region: eu-west-1
      accelerators: T4:4
      memory: 24+
    - region: eu-west-2
      accelerators: T4:4
      memory: 24+
    - region: eu-west-3
      accelerators: T4:4
      memory: 24+
    - region: eu-north-1
      accelerators: T4:4
      memory: 24+
```

What would be amazing if this would work too:
```
accelerators: [A10G:1, T4:4]
memory: 24+
ordered: 
    - region: eu-central-1
    - region: eu-west-1
    - region: eu-west-2
    - region: eu-west-3
    - region: eu-north-1
```
