### ISSUE TITLE
[Bug/Feature Request] sky serve doesn't respect regions bucket

### ISSUE THREAD

**Issue by manzke** [skypilot-org/skypilot#3114]
It seems sky serve doesn't respect the settings for the region. sky serve created a bucket in us-east-2 and tried to create a controller in the same regions. UPDATE: controller can be configured in config.yaml via serve section.

(Luckily it failed for me, because the specified vpc is only available in my zone)

# service.yaml
```
service:
  readiness_probe: /v1/models
 
resources: 
  use_spot: true
  replicas: 1
  memory: 24+
  ordered: 
    - region: eu-central-1
      accelerators: A10G:1
    - region: eu-central-1
      accelerators: T4:4
    - region: eu-west-1
      accelerators: A10G:1
    - region: eu-west-2
      accelerators: A10G:1
    - region: eu-west-3
      accelerators: A10G:1
    - region: eu-north-1
      accelerators: A10G:1
    - region: eu-west-1
      accelerators: T4:4
    - region: eu-west-2
      accelerators: T4:4
    - region: eu-west-3
      accelerators: T4:4
    - region: eu-north-1
      accelerators: T4:4
      memory: 24+
  
  ports: 
    - 8000

num_nodes: 1
workdir: .

file_mounts:
  ~/sky_workdir/openchat.jinja: openchat.jinja

setup: |
  conda create -n vllm python=3.9 -y
  conda activate vllm
  pip install vllm

run: |
  pwd
  ls -la /
  conda activate vllm
  python -m vllm.entrypoints.openai.api_server \
    --tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE \
    --host 0.0.0.0 --port 8000 \
    --model TheBloke/openchat-3.5-0106-AWQ \
    --served-model-name TheBloke/openchat_3.5-AWQ \
    --quantization awq \
    --chat-template openchat.jinja \
    --dtype auto
```

**Comment by cblmemo** [comment]
@manzke Thanks for reporting this! Actually the `resources` section under the Service YAML is the resources requirement for service replicas, not the controller. To specify controller resources, pls check here: https://skypilot.readthedocs.io/en/latest/serving/sky-serve.html#customizing-skyserve-controller-resources

**Comment by manzke** [comment]
You are right. the config.yaml and the service ones are confusing. It is not always clear. For example a sky serve controller for me is something specific to the task / service, but not in general.
Also tags for my instances are task / service specific, not general.

Btw the bucket is still generated in us-east-2. Why?

```
I 02-07 19:36:10 storage.py:1330] Created S3 bucket skypilot-workdir-danielmanzke-d64e0564 in us-east-2
I 02-07 19:36:13 storage.py:1330] Created S3 bucket skypilot-filemounts-files-danielmanzke-d64e0564 in us-east-2
```

**Comment by cblmemo** [comment]
> You are right. the config.yaml and the service ones are confusing. It is not always clear. For example a sky serve controller for me is something specific to the task / service, but not in general. Also tags for my instances are task / service specific, not general.
> 
> Btw the bucket is still generated in us-east-2. Why?
> 
> ```
> I 02-07 19:36:10 storage.py:1330] Created S3 bucket skypilot-workdir-danielmanzke-d64e0564 in us-east-2
> I 02-07 19:36:13 storage.py:1330] Created S3 bucket skypilot-filemounts-files-danielmanzke-d64e0564 in us-east-2
> ```

> the config.yaml and the service ones are confusing.

Thanks for sharing your feedback! We are thinking to have an controller resources override in service yaml. Does that sounds good to you? Or do you have other options in mind?

> Btw the bucket is still generated in us-east-2. Why?

Currently we won't limit the region of buckets - the `region` section is only for your cloud VMs. cc @romilbhardwaj @landscapepainter for a feature request here

**Comment by landscapepainter** [comment]
Hi @manzke thanks for the feedback! Do you mind sharing the use case for specifying the regions for the buckets? Would it be necessary for you to specify multiple different regions for buckets? Or a single region to specify is enough?

**Comment by manzke** [comment]
The use case is simple. 😁 I have all my resources in Europe. I'm running a German company and have to make sure all resources are in Frankfurt (or wherever I decide to host it).
I think the bucket should be close to the resources which is using it.

Example: a bucket in us-east and mounting it in a machine in Europe doesn't make sense at all.
Latency (regulatory) wise.

Also I'm sitting Europe, which could even to lead to a speed up. 

And if you have an instance with a bucket in the same region, you won't pay for traffic.

What's your use case for having buckets in us east and machines somewhere else? (Maybe I'm missing something) -> but I guess all your stuff is in us east anyway 😁

**Comment by vjsrinath** [comment]
@manzke I am also running into the similar issue. The s3 buckets are always created in us-east-2 because it was hard-coded to do so.
![image](https://github.com/skypilot-org/skypilot/assets/5001683/6a26f043-93e5-4ec8-818f-6e85567b32ff)
![image](https://github.com/skypilot-org/skypilot/assets/5001683/8163076d-f49a-4615-a0bd-25ebe69526bb)

The class [S3Store](https://github.com/skypilot-org/skypilot/blob/master/sky/data/storage.py#L1011) also defines the default region as us-east-2.

![image](https://github.com/skypilot-org/skypilot/assets/5001683/6b6e1caf-c934-4bb8-be24-6eb1fd2d9b33)

The region value is never passed to [_create_s3_backend ](https://github.com/skypilot-org/skypilot/blob/master/sky/data/storage.py#L1313) function. It appears to be a minor bug.

**Comment by romilbhardwaj** [comment]
For region-aware bucket creation, we need to:

1. Make bucket creation lazy (i.e., initialize bucket after the VM has been provisioned). That way we can know exactly which region to create the bucket in.
2. Add the plumbing to pass region info from upstream methods to the create bucket calls.

Two potential, but longer term optimizations:
1. Translation of regions between clouds (e.g., Illinois on fluidstack should create a bucket on us-east-1 on AWS).
2. With lazy bucket creation, parallelize file upload with setup/later stages of provisioning to maximize performance. 

We're looking for help on this, and would love to have PRs for this!

**Comment by vjsrinath** [comment]
@romilbhardwaj I would love to but there are a quite a lot of integrations to test.

Can we think about a short-term solution the region from resources requirements first? Would that be a viable option?

**Comment by concretevitamin** [comment]
Thanks for the report @vjsrinath! Could you share the YAML you used?

**Comment by vjsrinath** [comment]
sky/data/data_utils.py
![image](https://github.com/skypilot-org/skypilot/assets/5001683/dceb159c-0f0b-4135-9d4d-d1b659e3885d)
sky/data/storage.py
![image](https://github.com/skypilot-org/skypilot/assets/5001683/81c688a8-5e37-4612-90f9-03fa116d8c18)
sky/utils/controller_utils.py
![image](https://github.com/skypilot-org/skypilot/assets/5001683/78519be9-f9c2-4f3c-bc73-9529234294e3)

I started with the above changes. Am I on the right track? @concretevitamin @romilbhardwaj 
Thanks

**Comment by romilbhardwaj** [comment]
Thanks @vjsrinath - I'm not sure `region` should be an arg to `Storage`, but rather should be an arg to `AbstractStore` (The goal of Storage was to eventually encapsulate stores belonging to different stores/clouds/regions). It looks like it's already an arg there, but remains unused. 

I'll submit a PR fixing this issue by using the region specified in task resources (like you mentioned above). Stay tuned!

**Comment by vjsrinath** [comment]
@romilbhardwaj  Thanks for picking this up. The buckets are still not created based on the region specified in the resources section.

Task config:
```yaml
name: axolotl

resources:
  # accelerators: A100:8
  instance_type: p4d.24xlarge
  cloud: aws # optional
  region: us-east-1
  use_spot: True

workdir: train

file_mounts:
  /agp/datasets: ./datasets
  /sky-notebook:
    name: ${BUCKET}
    mode: MOUNT

setup: |
  docker pull winglian/axolotl:main-py3.10-cu118-2.0.1

run: |
  docker run --gpus all \
    -v ~/sky_workdir:/sky_workdir \
    -v /root/.cache:/root/.cache \
    winglian/axolotl:main-py3.10-cu118-2.0.1 \
    # huggingface-cli login --token ${HF_TOKEN}
  
  docker run --gpus all \
    -v ~/sky_workdir:/sky_workdir \
    -v /root/.cache:/root/.cache \
    -v /sky-notebook:/sky-notebook \
    winglian/axolotl:main-py3.10-cu118-2.0.1 \
    accelerate launch -m axolotl.cli.train /sky_workdir/models/mistral/mistral_domain-adapt_axolotl_lora.yaml

envs:
  HF_TOKEN: <your-huggingface-token> # TODO: Replace with huggingface token
  BUCKET: <a-unique-bucket-name-to-use>
```

Logs
```log

ask from YAML spec: axolotl-spot.yaml
I 03-25 20:05:10 storage.py:1386] Created S3 bucket llm-training-1 in us-east-2
I 03-25 20:05:10 storage.py:522] Verifying bucket for storage llm-training-1
Managed spot job 'axolotl-spot' will be launched on (estimated):
I 03-25 20:05:12 optimizer.py:690] == Optimizer ==
I 03-25 20:05:12 optimizer.py:701] Target: minimizing cost
I 03-25 20:05:12 optimizer.py:713] Estimated cost: $10.9 / hour
I 03-25 20:05:12 optimizer.py:713] 
I 03-25 20:05:12 optimizer.py:836] Considered resources (1 node):
I 03-25 20:05:12 optimizer.py:906] -------------------------------------------------------------------------------------------------
I 03-25 20:05:12 optimizer.py:906]  CLOUD   INSTANCE             vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-25 20:05:12 optimizer.py:906] -------------------------------------------------------------------------------------------------
I 03-25 20:05:12 optimizer.py:906]  AWS     p4d.24xlarge[Spot]   96      1152      A100:8         us-east-1c    10.91         ✔     
I 03-25 20:05:12 optimizer.py:906] -------------------------------------------------------------------------------------------------
I 03-25 20:05:12 optimizer.py:906] 
Launching the spot job 'axolotl-spot'. Proceed? [Y/n]: Y
I 03-25 20:05:15 controller_utils.py:423] Translating workdir and file_mounts with local source paths to SkyPilot Storage...
I 03-25 20:05:15 controller_utils.py:448] Workdir 'train' will be synced to cloud storage 'skypilot-workdir-vscode-775e2047'.
I 03-25 20:05:15 controller_utils.py:473] Folder in local file mount './datasets' will be synced to SkyPilot storage skypilot-filemounts-folder-vscode-775e2047-0.
I 03-25 20:05:15 controller_utils.py:521] Uploading sources to cloud storage. See: sky storage ls
E 03-25 20:05:16 storage.py:853] Could not create StoreType.S3 store with name skypilot-workdir-vscode-775e2047.
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

The above exception was the direct cause of the following exception:

sky.exceptions.StorageBucketCreateError: Attempted to create a bucket skypilot-workdir-vscode-775e2047 but failed.

During handling of the above exception, another exception occurred:

ValueError: Storage skypilot-workdir-vscode-775e2047 not found.
```
Command:
```sh
BUCKET=llm-training-1 sky spot launch -n axolotl-spot axolotl-spot.yaml --env BUCKET
```
