### ISSUE TITLE
[UX] Confusing logging for multiple resources

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3115]
Reported by a user:
The hints for invalid resources in multiple resources can be confusing:
```
resources:
  ordered: # Candidate resources in a preference order
    - region: eu-central-1
      accelerators: A10G:1
      memory: 64+
    - region: us-central2
      accelerators: A10G:1
      memory: 64+
```

```
I 02-07 16:58:38 optimizer.py:981] Using user-specified accelerators list (will be tried in the listed order): AWS(mem=64+, {'A10G': 1}), GCP(mem=64+, {'A10G': 1})
I 02-07 16:58:38 optimizer.py:1236] Try specifying a different memory size, or add "+" to the end of the memory size to allow for larger instances.
```

The second resourcse is invalid, but it is unclear what `Try specifying a different memory size, or add "+" to the end of the memory size to allow for larger instances.` refers to, as we already specify a memory with `+`.

One of the fix we should do is the `all_fuzzy_candidates` should be the fuzzy candidate for the current resource:
https://github.com/skypilot-org/skypilot/blob/905dd9c8a08c04e4f76378bcbd1f91ce1283a506/sky/optimizer.py#L1225-L1238
