### ISSUE TITLE
"Invalid value for field 'resource.scheduling.provisioningModel': 'STANDARD'. For preemptible, only allowed provisioning_model value is SPOT"

### ISSUE THREAD

**Issue by Kenadyi** [skypilot-org/skypilot#3235]
I have upgraded to the latest of sky version and i got the below error, even though i am using   "use_spot: true" in my yaml
Trying to launch multi node cluster 

21 05:15:20 provisioner.py:76] Launching on GCP us-west1 (us-west1-a)
W 02-21 05:15:26 instance_utils.py:112] Got return code 'invalid' in us-west1-a: "Invalid value for field 'resource.scheduling.provisioningModel': 'STANDARD'. For preemptible, only allowed provisioning_model value is SPOT"

**Comment by Kenadyi** [comment]
Sure here is the resources part in my yaml
```
resources:
  any_of:
    - cloud: aws
      region: us-west-2
      image_id:
        us-west-2: ami-0514bcd0cfc2aa8e2
      cpus: 2+
      memory: 4+
      disk_size: 50
      use_spot: true
    - cloud: gcp
      region: us-west1
      image_id: projects/mindful-rhythm-407109/global/machineImages/customcentos7-v4
      cpus: 2+
      memory: 4+
      disk_size: 50
      use_spot: true
num_nodes: 2

```
