### ISSUE TITLE
Allow setting the `workdir` using environment variables

### ISSUE THREAD

**Issue by mjkanji** [skypilot-org/skypilot#3271]
For situations when the working directory is not known in advance (e.g., on remote machines), it would be helpful to be able to dynamically populate the `workdir` value using an environment variable using the following syntax:

```yaml
envs:
  MY_WORKDIR: "some/path/"

workfir: ${MY_WORKDIR}
```
