### ISSUE TITLE
Cluster unable to get resource on Azure A10 Instance

### ISSUE THREAD

**Issue by binarycrayon** [skypilot-org/skypilot#3310]
resources requested
```
resources:
  cloud: azure
  ports: 8080
  accelerators: A10:1
  region: westus2
```
able to provision instance but blocked at `INFO: Waiting for task resources on 1 node. This will block if the cluster is full.`

```
======== Autoscaler status: 2024-03-13 21:41:27.656076 ========
Node status
---------------------------------------------------------------
Active:
 1 ray.head.default
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/1.0 A10
 0.0/6.0 CPU
 0B/31.73GiB memory
 0B/15.87GiB object_store_memory

Demands:
 {'CPU': 0.5, 'A10': 1.0, 'GPU': 1.0} * 1 (STRICT_SPREAD): 1+ pending placement groups
```
