### ISSUE TITLE
[Core] Support image id when using docker as runtime environment

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#3341]
One user mentioned that pulling the docker container is slow, and one way to alleviate this is supporting image_id when docker as runtime env is used: we could use an image with a local docker cache. Currently we use `image_id: docker:xxx` to specify using docker as runtime env. Could consider:

```yaml
resources:
  image_id:
    docker: <docker-image>
    <region>: <vm-image>
```
