### ISSUE TITLE
AWS Serving models insufficient permissions of skypilot role

### ISSUE THREAD

**Issue by SupermanAdam007** [skypilot-org/skypilot#3366]
skypilot config:
```
service:
  readiness_probe: /health
  replicas: 2

resources:
  cloud: aws
  region: us-east-1
  accelerators: A10G:1
  ports:
    - 8000

run: |
  sudo docker run --gpus all -p 8000:8000 ghcr.io/mistralai/mistral-src/vllm:latest \
                   --host 0.0.0.0 \
                   --model mistralai/Mistral-7B-v0.1 \
                   --tensor-parallel-size 1
```

gives me:

```
I 03-25 21:17:50 provisioner.py:76] Launching on AWS eu-west-1 (eu-west-1a,eu-west-1b,eu-west-1c)
C 03-25 21:17:51 utils.py:82] Failed to fetch IAM instance profile data for skypilot-v1 from AWS.
C 03-25 21:17:51 utils.py:82] Error code: AccessDenied
C 03-25 21:17:51 utils.py:83] 
E 03-25 21:17:51 utils.py:84] Boto3 error: {'response': {'Error': {'Type': 'Sender', 'Code': 'AccessDenied', 'Message': 'User: arn:aws:sts::975050348917:assumed-role/skypilot-v1/i-00d6a7f0f77e68ed5 is not authorized to perform: iam:GetInstanceProfile on resource: instance profile skypilot-v1 because no identity-based policy allows the iam:GetInstanceProfile action'}, 'ResponseMetadata': {'RequestId': '0161921f-aeac-47d5-8572-ebaa7e0e8b2e', 'HTTPStatusCode': 403, 'HTTPHeaders': {'date': 'Mon, 25 Mar 2024 21:17:50 GMT', 'x-amzn-requestid': '0161921f-aeac-47d5-8572-ebaa7e0e8b2e', 'content-type': 'text/xml', 'content-length': '489'}, 'RetryAttempts': 0}}, 'operation_name': 'GetInstanceProfile'} <built-in function exec>
```

After I added the following inline policy to `skypilot-v1` IAM role, it's working fine.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "iam:PassRole",
                "iam:GetInstanceProfile"
            ],
            "Resource": "*"
        }
    ]
}
```
