### ISSUE TITLE
[k8s] Log SkyPilot output to container stdout

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3429]
SkyPilot pods are run with `sleep infinity` to let SkyPilot runtime manage the lifecycle of the pod. As a result, container logs are empty `kubectl get logs`.

This causes problems when integrating with other log management systems running on the cluster, which directly scrape from the container logs. 

From user(s):
> We are using FileBeat for logs collection. Basically, all the pods' logs are automatically wrote into the dir /var/log/containers/ by k8s (the dir is on the host where the pod is running on), and we just configure this dir into FileBeat.
I found that when we use Sky, all the log files of LLM instances under /var/log/containers/ are just empty because Sky redirects logs
> Another user stated they use external logging system to collect logs of pods

Can we replace the `sleep infinity` command with something which monitors `~/sky_logs` and runs `tail` on any files that get created. Will need to handle multiple tasks executing simultaneously since their logs may get interleaved. 

## Workaround for now
Mount the `~/sky_logs`  to a local hostPath on the host machine. For example, if you add this to your `~/.sky/config.yaml`:
```
kubernetes:
  pod_config:
    spec:
      containers:
        - volumeMounts:
            - mountPath: /home/sky/sky_logs
              name: sky-logs-volume
              readOnly: false
      volumes:
        - name: sky-logs-volume
          hostPath:
            path: /var/log/sky_logs
            type: Directory
```

it will write all logs to /var/log/sky_logs on the host machine. Then you can add /var/log/sky_logs as a scrape path on your logging system. This is similar to how k8s writes all logs to /var/log/containers/.

For example, here's the directory structure that gets created when running two sky clusters independently:
```
/var/log/sky_logs$ tree # This is on the host machine
.
├── sky-2024-04-04-12-32-13-597156
│   ├── run.log
│   └── tasks
│       └── run.log
└── sky-2024-04-04-12-33-24-369770
    ├── run.log
    └── tasks
        └── run.log
```
Make sure you create the dir and make sure it has appropriate permissions (`mkdir -p /var/log/sky_logs; chmod -R 777 /var/log/sky_logs`) before mounting it.
