### ISSUE TITLE
[serve][docs] Documentation for `dynamic_ondemand_fallback` and `base_ondemand_fallback_replicas`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3440]
I'm wanting to use spot and/or on-demand instances (whichever are cheap and available) in my service spec:

```
resources:
  accelerators: T4:1 
  ports: 8888
  any_of:
    - use_spot: true
    - use_spot: false
```

`sky serve up` on this gives the following error:

```
ValueError: Resources must either all use spot or none use spot. To use on-demand and spot instances together, use `dynamic_ondemand_fallback` or set base_ondemand_fallback_replicas.
```

There's no documentation or explanation in code of what `dynamic_ondemand_fallback` or `base_ondemand_fallback_replicas` do and how to use them.
