### ISSUE TITLE
[Storage] Fail early for COPY mode storage field without source specified

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3477]
The following yaml will fail for `sky spot launch`, causing `FAILED_CONTROLLER` if the `zhwu-bucket-test-2` exist in the `sky storage ls` on laptop, but not on the spot controller.

```yaml
resources:
  cpus: 2+

file_mounts:
  test.yaml: test.yaml
  /my_mount:
    name: zhwu-bucket-test-2
    store: r2
    mode: COPY

run: |
  ls /my_mount/llm

```

Error:
```
(test-cloudflare, pid=8291) Process Process-1:
(test-cloudflare, pid=8291) sky.exceptions.StorageSourceError: New storage object: source must be specified when using COPY mode.
(test-cloudflare, pid=8291) I 04-24 22:46:42 controller.py:475] Killing controller process 23421.
(test-cloudflare, pid=8291) I 04-24 22:46:42 controller.py:483] Controller process 23421 killed.
(test-cloudflare, pid=8291) I 04-24 22:46:42 controller.py:485] Cleaning up any spot cluster for job 6.
(test-cloudflare, pid=8291) sky.exceptions.StorageSourceError: New storage object: source must be specified when using COPY mode.
ERROR: Job 6 failed with return code list: [1] 
```

The error should expose early when user calls `sky spot launch`, instead of waiting for the controller to be up and the job is scheduled.

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN
