### ISSUE TITLE
[Core] Support cross-cloud failover when labels are provided

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3500]
If a task specifies `labels`, it must currently specify the `cloud` to allow for checking labels since label validation varies across clouds. See [discussion here](https://github.com/skypilot-org/skypilot/pull/3464#discussion_r1580054387).

We may need a way to allow cross-cloud failover when resources are specified. 

Current workaround is to specify multiple clouds through `any_of` or `ordered` if failover with labels is desired:
```
resources:
  any_of:
    - cloud: gcp
      labels:
        cloud_name: gcp
    - cloud: kubernetes
      labels:
        my_domain/cloud_name: kubernetes
```
