### ISSUE TITLE
[SERVE] Add headers to the readiness probe

### ISSUE THREAD

**Issue by JGSweets** [skypilot-org/skypilot#3616]
If the serve function deploys a feature which utilizes authentication via headers, the readiness probe cannot interact with it.

Solution:
* update schema for `readiness_probe` to include a `headers` dictionary
* update `sky/serve/replica_managers.py::ReplicaInfo` to utilize headers when making the request.
* (optional) allow the schema to utilize the envs section to utilize values in the service

**Comment by Michaelvll** [comment]
This should be added in #3552, and we are adding the doc for it. Would you like to have a try for SkyPilot’s nightly build with `pip uninstall skypilot; pip install -U skypilot-nightly`

```
envs:
  AUTH_TOKEN: # left empty as a required filled during launch
services:
  readiness_probe:
    path: /v1/models
    # Set authorization headers here if needed.
    headers:
      Authorization: Bearer $AUTH_TOKEN
```
