### ISSUE TITLE
[Storage] Reusing externally deleted storage does not fail and succeeds with empty storage

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#3709]
When sky-managed storage is reused within task yaml while the actual storage from the backend is deleted externally, we currently move on after creating an empty storage with the specified `name` if `source` is not defined. `source` field not being specified in task yaml is allowed when reusing sky-managed storage and this may cause confusion to the users as they would be expecting to see the files in the original storage at the mount point of the remote instance. 

We may want to either raise an error to stop the `launch` of the task or log to note the users that the backend storage does not exist while launching so the users can re-launch after specifying the `source`.

This can be reprodced with the following steps:

1. `sky launch storage_task.yaml --cloud gcp -y`
2. externally remove sky managed storage 'my-storage' from the console
3. `sky launch reuse_storage_task.yaml --cloud gcp -y`

where `storage_task.yaml` is:
```
file_mounts:
  /mount_path:
    name: my-storage
    source: my-training-data
    store: gcs
```

and `reuse_storage_task.yaml` is:

```
file_mounts:
  /mount_path:
    name: my-storage
    store: gcs
```
