### ISSUE TITLE
[Storage] Regions are not respected for buckets created with `sky launch`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3744]
Repro:

```
resources:
  cloud: gcp
  region: europe-west1

file_mounts:
  /outputs:
    name: romil-4
    store: gcs
    mode: MOUNT
```

Bucket is created in US instead of europe-west1. Looks like #3319 solved for `sky jobs`/`sky serve`, but did not fix for `sky launch`.
