### ISSUE TITLE
[AWS] Updating AMI with Ubuntu 22.04 into skypilot:gpu-ubuntu-2204 ?

### ISSUE THREAD

**Issue by jucor** [skypilot-org/skypilot#3887]
Is it possible to have easy access to an AMI  with GPU support and Ubuntu 22.04, which amongst many things would provide  more recent Conda versions, please?

For example adding a new tag `skypilot:gpu-ubuntu-2204` that would point to the Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) , ID `ami-0b9dd033e4f035441` in us-west 2 -- and doing the same for the other regions too, instead of me doing it manually at the moment 😅

From https://github.com/skypilot-org/skypilot-catalog/blob/master/catalogs/v5/aws/images.csv It seems all the tags available in skypilot seem to be Ubuntu 20.04 or 18.04. Even Ubuntu 20.04 has an old version of conda, with the old slow solver (libmamba solver was added in Conda 23.10, available in Ubuntu 22.04).

Thanks a lot!

**Comment by jucor** [comment]
If it's any help, here's what I'm currently adding to my YAML:
```
image_id:
   eu-north-1: ami-00dac429de3db4247 # (Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) 20240823)
    eu-west-1: ami-07661c9ecd302a7aa # (Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) 20240823)
    eu-west-2: ami-07f2710a822ca329c # (Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) 20240823)
    eu-west-3: ami-0639bdc7fe95c8de0 # (Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) 20240823)
    us-east-1: ami-06e724c7e929de7ac # (Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) 20240823)
    us-east-2: ami-0c8cb6d6f6dc127c9 # (Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) 20240823)
    us-west-1: ami-083adcac3bd68800c # (Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) 20240823)
    us-west-2: ami-0b9dd033e4f035441 # (Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04) 20240823)
 ```
 
and a small script that I use to find the AMI ID:
```
#!/usr/bin/env bash

regions=(
    "eu-central-1"
    "eu-north-1"
    "eu-west-1"
    "eu-west-2"
    "eu-west-3"
    "us-east-1"
    "us-east-2"
    "us-west-1"
    "us-west-2"
)

ami_name="Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04)*"

for region in "${regions[@]}"; do
    ami_info=$(aws ec2 describe-images \
        --region "$region" \
        --owners amazon \
        --filters "Name=name,Values=$ami_name" \
        --query 'sort_by(Images, &CreationDate)[-1].[ImageId, Name]' \
        --output text)
    if [ ! -z "$ami_info" ]; then
        ami_id=$(echo "$ami_info" | cut -f1)
        ami_full_name=$(echo "$ami_info" | cut -f2)
        echo "$region: $ami_id # ($ami_full_name)"
    fi
done
```
