### ISSUE TITLE
[GCP] ultra disk fail to work with L4 GPUs

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3933]
```yaml
resources:
  accelerators: {L4, A10g, A10, A100, A100-80GB}
  cpus: 32+
  disk_tier: best
  ports: 8081  # Expose to internet traffic.
```

`sky launch --cloud gcp task.yaml` fails due to the following error:
```
W 09-11 18:54:20 instance_utils.py:112] Got return code 'badRequest' in asia-northeast3-a: '[pd-extreme] features and [instance_type: VIRTUAL_MACHINE\nfamily: GRAPHICS_OPTIMIZED\ngeneration: GEN_2\ncpu_vendor: INTEL\narchitecture: X86_64\n] InstanceTaxonomies are not compatible for creating instance'
```

We should avoid such error to ensure our LLM examples work as expected.

* `sky -c`: bad7dabf372f3512679098f63e4cfca8bc9b0870
