### ISSUE TITLE
[Serve] Inline update for readiness_probe

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3939]
I am trying to `sky serve update` with a new readiness_probe which I set it with the wrong one in the initial version, when the first two replicas are in `STARTING` stage. I expect after update with the correct readiness_probe, the replicas should become `UP`, but according to the `sky serve logs --controller` those initial replicas are still using the old readiness probe. We should fix this behavior.

To repro:
1. `sky serve up` with

<details>

<summary>yaml</summary>

```yaml
envs:
  MODEL_NAME: mistralai/Pixtral-12B-2409

service:
  replicas: 2
  # An actual request for readiness probe.
  readiness_probe:
    path: /v1/chat/completions
    post_data:
      model: $MODEL_NAME
      messages:
        - role: user
          content: "wrong format here"
      max_tokens: 1

resources:
  accelerators: {L40, L40S, A100, A100-80GB}
  cpus: 2+
  disk_tier: best
  ports: 8081  # Expose to internet traffic.

setup: |
  # Requires 0.6.1 for Pixtral support.
  pip install vllm==0.6.1

run: |
  echo 'Starting vllm api server...'

  export OMP_NUM_THREADS=8
  vllm serve $MODEL_NAME --tokenizer_mode mistral \
    --limit_mm_per_prompt 'image=4' \
    --max_num_batched_tokens 16384 \
    --max-model-len 10240 \
    --port 8081

```

</details>

2. When the replicas are in `STARTING` stage, `sky serve update` with

<details>

<summary>yaml</summary>

```yaml
envs:
  MODEL_NAME: mistralai/Pixtral-12B-2409

service:
  replicas: 2
  # An actual request for readiness probe.
  readiness_probe:
    path: /v1/chat/completions
    post_data:
      model: $MODEL_NAME
      messages:
        - role: user
          content:
            - type: text
              text: "Are you alive?"
      max_tokens: 1

resources:
  accelerators: {L40, L40S, A100, A100-80GB}
  cpus: 2+
  disk_tier: best
  ports: 8081  # Expose to internet traffic.

setup: |
  # Requires 0.6.1 for Pixtral support.
  pip install vllm==0.6.1

run: |
  echo 'Starting vllm api server...'

  export OMP_NUM_THREADS=8
  vllm serve $MODEL_NAME --tokenizer_mode mistral \
    --limit_mm_per_prompt 'image=4' \
    --max_num_batched_tokens 16384 \
    --max-model-len 10240 \
    --port 8081

```

</details>

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN
