### ISSUE TITLE
[R2] Mounting a R2 storage fail to work

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3945]
```
file_mounts:
  /data:
    name: skypilot-lmsys-chat-1m
    store: r2
    mode: MOUNT
```

`sky launch -c dev dev.yaml` fail to mount the R2 bucket in the yaml

Based on the command used for mounting the bucket, we seems using the wrong `Store` class for r2

```bash
...
goofys -o allow_other --stat-cache-ttl 5s --type-cache-ttl 5s skypilot-lmsys-chat-1m /data
...
```
