### ISSUE TITLE
[Jobs] API Design for DAG execution

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#4054]
We should think about the API to specify an DAG of tasks.

Several choices:

1. Add an attribute to `sky.Task` for predecessor/successor
2. Add a dedicated yaml file for node dependencies
3. Merge the node dependency yaml to the pipeline yaml

**Comment by cblmemo** [comment]
@andylizf seems like i cannot assign you to this issue. I assigned myself first

**Comment by andylizf** [comment]
How about this format?
```yaml
name: pipeline
depends_on:
  train: []
  eval: [train]
  analyze: [eval]
  visualize: [analyze, train]
---
name: train
resources:
  accelerators: V100:8
any_of:
  - use_spot: true
  - use_spot: false
file_mounts:
  /checkpoint:
    name: train-eval
    mode: MOUNT
setup: |
  echo setup for training
run: |
  echo run for training
  echo save checkpoints to /checkpoint
---
name: eval
resources:
  accelerators: T4:1
use_spot: false
file_mounts:
  /checkpoint:
    name: train-eval
    mode: MOUNT
setup: |
  echo setup for eval
run: |
  echo load trained model from /checkpoint
  echo eval model on test set
---
name: analyze
resources:
  cpus: 4
run: |
  echo analyze evaluation results
---
name: visualize
resources:
  cpus: 2
  memory: 16Gi
run: |
  echo create visualizations of results and training process
```
