### ISSUE TITLE
[k8s] Remote identity support when multiple contexts are configured

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#4131]
If I have multiple Kubernetes contexts configured in my `allowed_contexts`, I currently do not have a way to specify a different service account to be used (`kubernetes.remote_identity`) for each of these contexts.

E.g.:
```
kubernetes:
  allowed_contexts:
    - context1 # Uses service account named "sa1"
    - context2 # Uses service account named "sa2"
  remote_identity: # No way to specify different service accounts for each context.
```

We may need to make remote_identity of type `Union[dict[str,str], str]` which can either contain a dict mapping context names to service accounts or a singular service account name to be used for all contexts (current behavior).
