### ISSUE TITLE
[UI] Empty Accelerator should raise an issue

### ISSUE THREAD

**Issue by MaoZiming** [skypilot-org/skypilot#4153]
```
resources:
  accelerators: # Fill in the accelerator type
  cpus: 16+
  memory: 32+
```
