### ISSUE TITLE
[k8s] Add validation for `pod_config`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#4206]
When users specify `pod_config` in their config.yaml, they may make syntax errors which are not caught until later in the provisioning flow. 

We should add early validation/schema checks for the `pod_config` field.

**Comment by romilbhardwaj** [comment]
Closed with #4466.

**Comment by romilbhardwaj** [comment]
This is broken as of current master (3d0681720d71085d55e2765f09716827a4180ffd).

This task can be launched - it should raise an error.

```
resources:
  cloud: kubernetes

run: |
  echo hi

config:
  kubernetes:
    provision_timeout: 600
    pod_config:
      spec:
        somedata: echohi
```
