### ISSUE TITLE
[k8s] pod resource limit

### ISSUE THREAD

**Issue by bgyoon** [skypilot-org/skypilot#4242]
In our setup, we’ve installed a Kubernetes cluster on an H100 node and are using SkyPilot to manage resource sharing.

I realized that the cpu and memory specifications in the Task YAML are resource requests and not limits. While this approach might make sense in public cloud use cases, it can introduce issues within a Kubernetes backend.

For instance, if a task requests 20GB of memory without a defined limit, it has the potential to consume all available memory on the node, causing an OOM error on everything running on that node.

I believe, I could explicitly set both requests and limits like so:

```
resources:
  cloud: kubernetes
  accelerators: H100:1
  cpus: 20
  memory: 200

experimental:
  config_overrides:
    kubernetes:
      pod_config:
        spec:
          containers:
            - resources:
                requests:
                  cpu: "20"
                  memory: "200Gi"
                limits:
                  cpu: "20"
                  memory: "200Gi"
```

However, this approach requires editing multiple configurations each time I update the pod spec. I think a more intuitive approach would be to have resources: cpus and memory in the Task YAML directly map to requests and limits in the pod spec.
