### ISSUE TITLE
runpod docker credentials not working when using image_id from private repository

### ISSUE THREAD

**Issue by alita-moore** [skypilot-org/skypilot#4269]
Because runpod doesn't support docker I need to use my docker image as the base image_id but setting the `SKYPILOT_DOCKER_USERNAME` and `SKYPILOT_DOCKER_PASSWORD` doesn't allow the created runpod to have access to the private repo. However, if you manually change the dockerhub config on the runpod web UI (which I setup beforehand) it works fine. Is there a way to authenticate the docker image for the created pod automatically?

For reference here's my config:
```
resources:
  image_id: docker:teamwoven/convert:sultan-1.0
  cloud: runpod
  ports: 8000
  accelerators: RTX4090:1

service:
  readiness_probe: /status

envs:
  SKYPILOT_DOCKER_USERNAME:
  SKYPILOT_DOCKER_PASSWORD:
  SKYPILOT_DOCKER_SERVER: docker.io

setup: |
  #

run: |
  # Run the FastAPI server with two workers
  /home/woven/.local/bin/uvicorn extractor_inference.app:app --host "0.0.0.0" --port 8000 --workers 2
```

and then an image of the runpod UI that I'm referring to:
<img width="976" alt="Screenshot 2024-11-07 at 5 18 01 AM" src="https://github.com/user-attachments/assets/7c71a1d7-4c51-4674-a620-a917a663b187">

_Version & Commit info:_
* `sky -v`: skypilot, version 0.7.0
* `sky -c`: 3f625886bf1b13ee463a9f8e0f6741f620f7f66f
