### ISSUE TITLE
[Fluidstack] sky launch can leak instances when instance creation times out

### ISSUE THREAD

**Issue by Xe** [skypilot-org/skypilot#4392]
With a config like this:
```yaml
resources:
  accelerators: [A100:1]
  cloud: fluidstack

setup: "echo hi"

run: "python -m http.server 8080"
```

Fluidstack instance creation fails and the instances in the cloud are unable to be destroyed. The panel returns a "try again in 60 seconds" 500 error with this JSON body:

```json
{"message":"Unable to terminate instance. Please try again in 60 seconds."}
```

_Version & Commit info:_
* `sky -v`: `skskypilot, version 1.0.0.dev20241031`
* `sky -c`: `skypilot, commit c4eeeb5fb3ef64be0f05a727e119ac9266f8940f`
