### ISSUE TITLE
[chore] Deprecate `sky launch --docker`

### ISSUE THREAD

**Issue by gaocegege** [skypilot-org/skypilot#4508]
Running sky launch --docker creates two clusters: one is expected, while the INIT cluster cannot be stopped or torn down.

```sh
(base) ➜  skypilot git:(f0ebf13b) ✗ sky status
Clusters
NAME           LAUNCHED     RESOURCES  STATUS  AUTOSTOP  COMMAND
b103-gcgg      2 mins ago   docker     UP      -         sky launch ./hello-sky/he...
sky-b103-gcgg  2 mins ago   docker     INIT    -         sky launch ./hello-sky/he...
(base) ➜  skypilot git:(f0ebf13b) ✗ sky stop b103-gcgg
Stopping 1 cluster: b103-gcgg. Proceed? [Y/n]: y
Stopping 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--LocalDockerBackend.teardown() will terminate containers for now, despite receiving terminate=False.
Stopping cluster b103-gcgg...done.
  To restart the cluster, run: sky start b103-gcgg
Stopping 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
(base) ➜  skypilot git:(f0ebf13b) ✗ sky stop sky-b103-gcgg
Stopping 1 cluster: sky-b103-gcgg. Proceed? [Y/n]: y
Stopping 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--LocalDockerBackend.teardown() will terminate containers for now, despite receiving terminate=False.
Stopping cluster sky-b103-gcgg...done.
  To restart the cluster, run: sky start sky-b103-gcgg
Stopping 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
(base) ➜  skypilot git:(f0ebf13b) ✗ sky status
Clusters
NAME           LAUNCHED     RESOURCES  STATUS  AUTOSTOP  COMMAND
sky-b103-gcgg  3 mins ago   docker     INIT    -         sky launch ./hello-sky/he...
```

Here is the task yaml:

```yaml
# Task name (optional), used for display purposes.
name: my-task

resources:
  # Optional; if left out, automatically pick the cheapest cloud.
  cloud: kubernetes

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: .

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  echo "Hello, SkyPilot!"
  conda env list
```

_Version & Commit info:_
* `sky -v`: skypilot, version 1.0.0-dev0
* `sky -c`: skypilot, commit f0ebf13b5b164d012f4b033609eb1b364dc6caf3
