### ISSUE TITLE
[Jobs/Serve] SkyServe uses intermediate bucket specified in `jobs.bucket`

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#4559]
`sky serve up -n http task.yaml`  somehow uses the intermediate bucket specified in `jobs.bucket`

```yaml
# ~/.sky/config.yaml
jobs:
  bucket: gs://test-zhwu-jobs-intermediate
```

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN
