### ISSUE TITLE
Restart an INIT cluster skips file_mounts and setup

### ISSUE THREAD

**Issue by aylei** [skypilot-org/skypilot#4728]
## Actual Behavior

Launched a cluster but failed when syncing file mounts:

```
$ sky launch -c aylei-cs api-server-test.yaml
YAML to run: api-server-test.yaml
Considered resources (1 node):
---------------------------------------------------------------------------------------------
 CLOUD   INSTANCE      vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN
---------------------------------------------------------------------------------------------
 AWS     c6i.2xlarge   8       16        -              ap-southeast-1   0.39          ✔
---------------------------------------------------------------------------------------------
Launching a new cluster 'aylei-cs'. Proceed? [Y/n]: Y
⚙︎ Launching on AWS ap-southeast-1 (ap-southeast-1a,ap-southeast-1b,ap-southeast-1c).
├── Instance is up.
└── Docker container is up.
Open file descriptor limit (256) is low. File sync to remote clusters may be slow. Consider increasing the limit using `ulimit -n <number>` or modifying system limits.
✓ Cluster launched: aylei-cs.  View logs: sky api logs -l sky-2025-02-16-22-16-56-301393/provision.log
⚙︎ Syncing files.
  Syncing (to 1 node): /Users/aylei/repo/skypilot-org/skypilot -> ~/.sky/file_mounts/sky_repo
sky.exceptions.CommandError: Command rsync -Pavz --filter='dir-merge,- .gitignore' -e 'ssh -i /Users/aylei/.sky/clients/57339c81/ssh/sky-... failed with return code 255.
Failed to rsync up: /Users/aylei/repo/skypilot-org/skypilot -> ~/.sky/file_mounts/sky_repo. Ensure that the network is stable, then retry.
```

Restarted the cluster in `INIT` state:

```
sky start aylei-cs

Restarting 1 cluster: aylei-cs. Proceed? [Y/n]: Y
⚙︎ Launching on AWS ap-southeast-1 (ap-southeast-1a).
├── Instance is up.
└── Docker container is up.
Open file descriptor limit (256) is low. File sync to remote clusters may be slow. Consider increasing the limit using `ulimit -n <number>` or modifying system limits.
✓ Cluster launched: aylei-cs.  View logs: sky api logs -l sky-2025-02-16-22-23-19-710647/provision.log
Cluster aylei-cs started.
```

SSH to the cluster, observed no `/sky_repo` mounted and no setup executed.
```
ssh aylei-cs
ls /sky_repo
ls: cannot access '/sky_repo': No such file or directory
```

## Expected Behavior

I expect skypilot either:

- setup `file_mounts` and run setup job idempotently on restart
- warns user that the state might be broken when restarting a cluster in `INIT` state and hint user re-launch the cluster (`sky down && sky launch`)  to get a clean state

## Appendix

The sky yaml I used:

```yaml
resources:
  cloud: aws
  cpus: 8+
  memory: 16+
  ports: 46580
  image_id: docker:berkeleyskypilot/skypilot-beta:latest
  region: ap-southeast-1

file_mounts:
  /sky_repo: /Users/aylei/repo/skypilot-org/skypilot
  ~/.ssh/id_rsa.pub: ~/.ssh/id_rsa.pub

envs:
  SKYPILOT_POD_CPU_CORE_LIMIT: "7"
  SKYPILOT_POD_MEMORY_GB_LIMIT: "14"

setup: |
  cd /sky_repo
  pip install -r requirements-dev.txt
  pip install -e .[aws]

  mkdir -p ~/.sky

  # Add any custom config here
  cat <<EOF > ~/.sky/config.yaml
  allowed_clouds:
    - gcp
    - aws
    - kubernetes
  EOF
  sky api start --deploy
```
