### ISSUE TITLE
[UX][API Server] Store historical API server url for faster switching

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#4747]
I found myself constantly switching between local server & a remote server. If we can support `sky api login -e SERVER_ENDPOINT -n remote` and quickly switch back by `sky api login -n remote`, that would be way more convenient for copy pasting the url again.

Additionally, a shortcut `-n local` for loca api server would be convenient.

**Comment by Michaelvll** [comment]
Good point! We can follow what Kubernetes have for contexts.

Maybe something like
```
api_server:
    endpoint:
        endpoint1: http://xxx
        my-endpoint2: http://yyy
```
