### ISSUE TITLE
[k8s] Allow `sky local up` to create multiple k8s

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#4794]
When a user have multiple instances that need to set multiple k8s. Currently, they have to run `sky local up` multiple times to setup k8s on each of them. We should allow specifying multiple ip list and keys to setup k8s on all of them, e.g.:

```yaml
clusters:
  my-cluster-1:
    ips:
      - xxx
      - xxx
      - xxx
    key_file: xxx
  my-cluster-2:
    ips:
      - yy
      - yyy
      - yyyy
    key_file: yyy

```
