### ISSUE TITLE
Docker runtime environment is polluted with env variables from skypilot setup

### ISSUE THREAD

**Issue by v-lopez** [skypilot-org/skypilot#4814]
Running my container fails because some python modules fail to be imported, this environment is set through conda so I believe it may be conflicting with the conda environment set there.
Printing the environment I see some exports that are not there when the container is run without skypilot.
```
CONDA_PREFIX=/root/miniconda3
CONDA_PROMPT_MODIFIER=(base) 
CONDA_DEFAULT_ENV=base
```

I tried completely clearing the environment as a workaround, but then I am missing NVIDIA env variables.

Unsetting those 3 variables in my execute script solves the issues.

This is somewhat new I believe, I did not have this issues 2 weeks ago, I am running skypilot nightly.

**Comment by aylei** [comment]
Hi @v-lopez ! How do you setup skypilot in your container? Are you using skypilot as the base image or installing skypilot in your build process? It would be helpful if you can provide the commands you ran before hitting the issue

**Comment by v-lopez** [comment]
I don't set it up in the container, this is my task.yaml

```
resources:
  image_id: docker:MY_IDdkr.ecr.eu-central-1.amazonaws.com/org/image:tag
  accelerators: {RTX3090-TI:1, RTX3090:1, A10G:1}
  cpus: 4+
  memory: 16+
  disk_size: 100
  any_of:
    - cloud: aws
      region: eu-central-1
    - cloud: kubernetes

workdir: .

setup: |
  echo "Running setup." 

run: |
  /root/execute_script.sh
```
The image is built from nvcr.io/nvidia/isaac-sim:4.2.0 which is the one that runs the conda environment.

The execute_script.sh just runs isaac lab (a simulator for reinforcement learning)
```
#!/bin/bash

cd /ws/IsaacLab 
./isaaclab.sh -p source/standalone/workflows/rsl_rl/train.py \
    --task=Isaac-Cartpole-v0 \
    --headless \
    --logger wandb \
    --log_project_name test1 \
    --video \
    --video_length 200 \
    --video_interval 50
```
