### ISSUE TITLE
[Serve] Multiple LB in the same service

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#4869]
In [this comment](https://github.com/skypilot-org/skypilot/issues/3727#issuecomment-2693147896), a user requires multiple LB in one single service. One possible approach would be follow [this design](https://github.com/skypilot-org/skypilot/pull/4356#issuecomment-2590968770):

```yaml
service:
  ports:
    - 8000,9000 # Indicating there will be one LB for all IP + Port pairs, if Port == 8000 or 9000
    - 10000-10100,7888 # if port in [10000,10100] or port == 7888
    - 7000 # Indicating a LB for all IP:7000
```
