### ISSUE TITLE
[k8s] `sky status --k8s` does not take `kubernetes.allowed_contexts` into account.

### ISSUE THREAD

**Issue by abrahamcl** [skypilot-org/skypilot#4870]
With multiple kubernetes contexts configured, `sky status --k8s` will use the current context even if it is not specified in `kubernetes.allowed_contexts`.

```yaml
# ~/.kube/config
...
contexts:
- context:
      ...
  name: skypilot
- context:
      ...
  name: notskypilot
current-context: notskypilot
...
```

```yaml
# ~/.sky/config.yaml
kubernetes:
  allowed_contexts: 
    - skypilot
```

The previous configuration allows me to successfully `sky check kubernetes`, but `sky status --k8s` tries to use the `notskypilot` context.
