### ISSUE TITLE
Disk size not set as expected for TPUs

### ISSUE THREAD

**Issue by briantliao** [skypilot-org/skypilot#4964]
I specified 300 GB in my config.yaml, but my TPU only has 100 GB, which seems to be the default: https://cloud.google.com/tpu/docs/storage-options#:~:text=By%20default%2C%20each%20Cloud%20TPU,space%20on%20the%20boot%20disk.

Checking GCP console, no disks were created.

# Reproduce

`skypilot_config.yaml`:
```yaml
name: resnet-50-on-imagenet-1k
workdir: .

resources:
  cloud: gcp 
  accelerators: tpu-v6e-1
  use_spot: true 
  disk_size: 300

setup: |
  echo "Begin setup."
  pip install -r requirements.txt
  echo "Setup complete."
```

Locally run `sky launch -c resnet-50-on-imagenet-1k skypilot_config.yaml`

In vm
```
df -h
Filesystem       Size  Used Avail Use% Mounted on
/dev/root         97G   97G     0 100% /
tmpfs             87G   36K   87G   1% /dev/shm
tmpfs             35G   26M   35G   1% /run
tmpfs            5.0M     0  5.0M   0% /run/lock
efivarfs          56K   24K   27K  48% /sys/firmware/efi/efivars
/dev/nvme0n1p15  105M  6.1M   99M   6% /boot/efi
tmpfs             18G  4.0K   18G   1% /run/user/2001
```
