### ISSUE TITLE
[AWS][Config] Ability to provide a list of security groups

### ISSUE THREAD

**Issue by JGSweets** [skypilot-org/skypilot#4976]
Currently, we are limited to providing one security group per instance. It would be ideal if we could provide a list instead.

### Curent Format

```yaml
aws:
  # Format 1
  security_group_name: my-security-group

  # Format 2
  security_group_name:
    - my-cluster-name: my-security-group-1
    - sky-serve-controller-*: my-security-group-2
    - "*": my-default-security-group
```

### Desired Format

```yaml
aws:
  # Format 3
  security_group_name:
    - my-cluster-name: 
      - my-cluster-security-group-1
      - my-cluster-security-group-2
    - sky-serve-controller-*: 
      - my-controller-security-group-1
      - my-controller-security-group-2
    - "*": my-default-security-group
```
