### ISSUE TITLE
Cannot control job parallelism using `cpus`

### ISSUE THREAD

**Issue by qw3rtman** [skypilot-org/skypilot#4984]
Thanks for the great work on SkyPilot.

When I submit a job to a cluster with `--cpus=1`, it seems to be ignored (`Override param cpus=1 is ignored.`). This is evidenced by the number of running jobs greatly exceeding the number of workers...

The `--gpu=n` parameter is obeyed. Is there a recommended way to limit the number of jobs running at a time to some CPU or RAM capacity?

yaml excerpt below
```yaml
num_nodes: 16
resources:
  cloud: gcp
  cpus: 1+
```

**Comment by cg505** [comment]
Can you clarify the steps you took? That is, how did you launch the cluster, then what commands/yaml you used to submit the jobs to the cluster?

**Comment by qw3rtman** [comment]
Launched via `sky launch -c train train.yaml`

```yaml

num_nodes: 16
resources:
  cloud: gcp
  cpus: 1+
  any_of:
    - region: us-central1
    - region: us-east1
    - region: us-east4
    - region: us-east5
    - region: us-south1
    - region: us-west1
    - region: us-west2
    - region: us-west3
    - region: us-west4

setup: |
  conda create -n train python=3.10 -y
  conda activate train
  curl -LsSf https://astral.sh/uv/install.sh | sh
  source $HOME/.local/bin/env
  uv pip install datasets wandb ipython jupyter gcsfs intervaltree
  pip install verdict

run: |
  conda activate train
  echo "Ready!"
```

Submitted tasks via
```sh
sky exec star-train -d --cpus=1 -- python -m train.py ...`
```

**Comment by qw3rtman** [comment]
Launched via `sky launch -c train train.yaml`

```yaml

num_nodes: 16
resources:
  cloud: gcp
  cpus: 1+
  any_of:
    - region: us-central1
    - region: us-east1
    - region: us-east4
    - region: us-east5
    - region: us-south1
    - region: us-west1
    - region: us-west2
    - region: us-west3
    - region: us-west4

setup: |
  conda create -n train python=3.10 -y
  conda activate train
  curl -LsSf https://astral.sh/uv/install.sh | sh
  source $HOME/.local/bin/env
  uv pip install datasets wandb ipython jupyter gcsfs intervaltree
  pip install verdict

run: |
  conda activate train
  echo "Ready!"
```

Submitted tasks via
```sh
sky exec train -d --cpus=1 -- python -m train.py ...`
```
