### ISSUE TITLE
[GCP] GCS storage no longer works with owner role

### ISSUE THREAD

**Issue by aylei** [skypilot-org/skypilot#5020]
I have an API server deployed with a GCP credentials that has project owner role, it cannot longer use GCS file_mounts as before:

cluster.yaml:
```yaml
resources:
  cloud: kubernetes
  cpus: 2+

file_mounts:
  /my_data:
    name: $NEW_BUCKET
    store: gcs

setup: |
  echo "From FUSE" >  /my_data/test.txt

run: |
  cat /my_data/test.txt
```

`sky launch`:

```
sky launch -c gcs cluster.yaml -y
YAML to run: gcs-create.yaml
Running on cluster: gcs2
sky.exceptions.ResourcesUnavailableError: Storage 'store: gcs' specified, but GCP access is disabled. To fix, enable GCP by running `sky check`. More info: https://docs.skypilot.co/en/latest/getting-started/installation.html.
```

`sky check`:

```
  GCP: enabled [compute]
    Reason [storage]: The following permissions are not enabled for the current GCP identity (apiserverbeta@sky-dev-***.iam.gserviceaccount.com [project_id=sky-dev-***]):
    {'storage.objects.delete', 'storage.objects.create', 'storage.objects.get', 'storage.buckets.get', 'storage.objects.update', 'storage.objects.list'}
    For more details, visit: https://docs.skypilot.co/en/latest/cloud-setup/cloud-permissions/gcp.html
```

The listed permissions `{'storage.objects.delete', 'storage.objects.create', 'storage.objects.get', 'storage.buckets.get', 'storage.objects.update', 'storage.objects.list'}` are usually granted at bucket level, which might be the reason that the permission check failed on the IAM role.

Might be related to https://github.com/skypilot-org/skypilot/pull/4977, cc @SeungjinYang
