### ISSUE TITLE
Issues with Vast cloud

### ISSUE THREAD

**Issue by samhaaf-broomstick** [skypilot-org/skypilot#5022]
I'm launching with this config:

```
resources:
  accelerators: RTXA6000  
  # ports: 
  #   - 8888
  #   - 4000
  #   - 8188
  disk_size: 120

num_nodes: 1 

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: ./deps

# Commands to be run before executing the job.
# Typical use: pip install -r requirements.txt, git clone, etc.
setup: |
  # make install


# Commands to run as a job.
# Typical use: launch the main program.
run: |
  make run
```

And I'm having two issues:

1. I can't specify any ports. It sems like the Vast implementation supports ports, because when I set them then sky can't find any options to meet the resource requirements.

2. No matter what I set the disk_size to, it always allocates a size of 10GB

IFT: This is my first skypilot project.
