### ISSUE TITLE
[AWS] Ability to specify the min and max count per zone.

### ISSUE THREAD

**Issue by JGSweets** [skypilot-org/skypilot#5070]
Skypilot allows you to specify both capacity reservations and zones for resources. Reservations can be limited / dedicated to a specific zone.

When launching new jobs or services, it would be ideal to require a the minimum capacity or maximum capacity per zone to ensure those reservations are met.

Example:
```
resources:
  cloud: AWS
  region: <REGION>
  zones:
    <zone1>:
        min: <int>
        max: <int>
    <zone2>:
        min: <int>
        max: <int>
```

This would ensure on a new launch the reservations in specific zones are met each time. Otherwise, if there is 1 in each zone, it is possible for Skypilot to put 2 resources in one zone when the reservations are spread across multiple.
