### ISSUE TITLE
conda environment activated in custom docker image

### ISSUE THREAD

**Issue by cg505** [skypilot-org/skypilot#5265]
>I am specifying my image in that resource location and my image is being pulled, which is hosted on google cloud container registry. I am still seeing it enable base conda on the run section, and I'm having to do 'conda deactivate'. 
>
>I'm not sure if it's because it isn't pulling directly from docker that it's not trigger the flag, or if I'm missing something. 
>
>We're on v1.0.0.dev20250405

_Originally posted by @scm-aiml in https://github.com/skypilot-org/skypilot/issues/3874#issuecomment-2812918535_

**Comment by Michaelvll** [comment]
Duplicated with #4814?

**Comment by romilbhardwaj** [comment]
I can't repro with:
```
resources:
  cloud: gcp
  image_id: docker:vllm/vllm-openai:latest

run: |
  which python
 # Does not print any python path since the base image doesn't have it. 
```

I was concerned this may be a blocker for 0.9.0, but doesn't look like it.
