### ISSUE TITLE
[storage] storage upload failing due to "Argument list too long"

### ISSUE THREAD

**Issue by SeungjinYang** [skypilot-org/skypilot#5281]
![Image](https://github.com/user-attachments/assets/7ea9b55c-a7a1-43bf-9374-32710728bf40)

`/bin/bash: /opt/homebrew/bin/aws: Argument list too long`

Investigate the following error message when uploading files to cloudflare R2 storage

**Comment by SeungjinYang** [comment]
Tried reproducing this with:
```
file_mounts:
  /cloudflare:
    name: <bucket-name>
    source: ~/yamls
    store: r2
    mode: MOUNT
```
This command actually errors out for me with
`upload failed: ../../yamls/cloudflare.yaml to s3://<bucket-name>/cloudflare.yaml An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error. Please try again.`

but I am not getting the error described in the issue.
