### ISSUE TITLE
python executable not found when running a docker image with Runpod

### ISSUE THREAD

**Issue by SeungjinYang** [skypilot-org/skypilot#5306]
```
service:
  readiness_probe: /healthcheck
  replica_policy:
    min_replicas: 2
    max_replicas: 12
    target_qps_per_replica: 10

resources:
  image_id: docker:pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
  cloud: runpod
  region: US
  ports: 8000
  cpus: 4+
  memory: 8+
  disk_size: 32
  accelerators:
    - RTX4090
  use_spot: false

setup: |
  pip install --upgrade pip setuptools
  pip install --no-cache-dir -r requirements.txt

run: |
  python main.py
```
Here is the skypilot YAML. The base image, when run standslone, does return an entry for `which python`.
