### ISSUE TITLE
Ray head node defaulting to `--num-cpus 500m` (invalid value for `--num-cpus`)

### ISSUE THREAD

**Issue by turtlebasket** [skypilot-org/skypilot#5315]
(On `1.0.0.dev20250413`) I'm encountering:

```
RuntimeError: Failed to start ray on the head node (exit code 1). Error: 
===== stdout ===== 
2025-04-22 23:07:08,623 INFO scripts.py:1163 -- Did not find any active Ray processes.
Usage: ray start [OPTIONS]
Try 'ray start --help' for help.

Error: Invalid value for '--num-cpus': '500m' is not a valid integer.

===== stderr =====command terminated with exit code 1
```

…when running `sky serve up service.yml --env-file <env>` with the below config:

```yaml
service:
  readiness_probe: /healthcheck
  replica_policy:
    min_replicas: 2
    max_replicas: 12
    target_qps_per_replica: 10
  tls:
    certfile: certs/skyserve.crt
    keyfile: certs/skyserve.key

resources:
  image_id: docker:pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
  cloud: runpod
  region: US
  ports: 8000
  cpus: 4+
  memory: 8+
  disk_size: 32
  accelerators:
    - RTX4090
  use_spot: false

workdir: .

envs:
  HF_TOKEN: ${HF_TOKEN}
  HF_MODEL: ${HF_MODEL}

setup: |
  # <many (valid) setup commands>

run: |
  source /venv/bin/activate
  python main.py
```

Strangely, the above deployment config was working perfectly a day or two ago—this behavior basically appeared overnight with no new config changes on my end. My first thought was this could be the controller, but my sky config specifies a 1 core and 2G mem, so I don't think the controller is the cause of the fractional-core param being passed in here...
