### ISSUE TITLE
[Multi-k8s] Use different configuration for different k8s contexts

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#5353]
### Discussed in https://github.com/skypilot-org/skypilot/discussions/5352

<div type='discussions-op-text'>

<sup>Originally posted by **SchKng** April 24, 2025</sup>
Hi all,

I'm currently setting up skypilot for our org. and I'm running into some limitations with the way kubernetes is handled at the `config.yaml` level.

### Our setup

Here's a summary of our setup:
- 3 kubernetes clusters
  - GKE (on GCP)
  - EKS (on AWS)
  - K3S (on-prem, deployed with `sky local up`)
- Sky API server deployed remotely (multi-user teams)

### Kubernetes contexts management

As for as I understand, kubernetes is handled as a single cloud through the `config.yaml` file.
Each kubernetes cluster has to be added in the `allowed_contexts` of the kubernetes section of the config.

I'm going to take the example of the autoscaling configuration to illustrate my point.
If I want to enable the autoscaling feature, I can only do it at the "kubernetes" level in the `config.yaml` deployed in the API server:
```
kubernetes:
  allowed_contexts:
    - gke_context
    - eks_context
    - on_prem_context
  provision_timeout: 900
  autoscaler: gke
```

Let's say I want to force a job / cluster to run on our EKS cluster (`--cloud k8s --region eks_context`).
As it stands, given the previous config on the remote API server, it will try to use the GKE autoscaling feature to try to provision and fail.

Of course, I could override the configuration through the cli or through my local `config.yaml` (as specified [here](https://docs.skypilot.co/en/latest/reference/config-sources.html#configuration-overrides)).
However, as an admin of the whole thing, I'd like to be able to manage all this within the `config.yaml` of the remote API server, not hope that users don't forget changing or overriding the config !

### Benefits & design proposal

This could also have other benefits such as specifying a different service account / custom_metadata / ... for each k8s context, basically all of the kubernetes options offered in the `config.yaml`.

A proposal could be to have something like:
```
kubernetes:
  gke_context:
    autoscaler: gke
    provision_timeout: 600
    remote_identity: my-gke-service-account
  eks_context:
    autoscaler: xxx
    remote_identity: my-eks-service-account
  on_prem_context:
    autoscaler: none
    provision_timeout: 300
```

Please let me know if I missed something or if there's another way to do that.
Thanks a lot!

</div>

**Comment by schkng** [comment]
Hi everyone,

I've started working on the issue and here's a proposal for the design of the config file (example):
```
kubernetes:
  allowed_contexts:
    - my_context_1
    - my_context_2
  
  contexts_overrides:
    my_context_1:
      autoscaler: gke
      ...

    my_context_2:
      provision_timeout: 60
      ...

  autoscaler: generic
```

I'm proposing keeping the `allowed_contexts` property not to introduce breaking changes.

Regarding properties order / priority in the config, it'd be like this:
1. default properties for all contexts
2. properties specified at `kubernetes` level for all contexts
3. override of properties for each context & property in `contexts_overrides/context/property`

In this example, the final configuration of the contexts would be:
- my_context_1:
  - autoscaler: gke (overriden in contexts_overrides/my_context_1/autoscaler)
  - provision_timeout: 10 (default value)
- my_context_2:
  - autoscaler: generic (specified at kubernetes level)
  - provision_timeout: 60 (overriden in contexts_overrides/my_context_2/provision_timeout)

**Comment by cg505** [comment]
@romilbhardwaj FYI

**Comment by SeungjinYang** [comment]
Nice! I do see a future world where `allowed_contexts` can be made redundant and deprecated. What do you think about we rename `contexts_overrides` to `context`, like such:

```
kubernetes:
  allowed_contexts:
    - my_context_1
    - my_context_2
  
  contexts:
    my_context_1:
      autoscaler: gke
      ...

    my_context_2:
      provision_timeout: 60
      ...

  autoscaler: generic
```

and define the behavior as:
- If context is specified in `allowed_contexts` and `contexts`, then the context is allowed and any context-specific fields are applied
- If context is only specified in `allowed_contexts`, then the context is allowed and there is no context-specific field applied to the context. Properties specified at kubernetes level for all contexts is still applied.
- If context is only specified in `contexts`, then the context is allowed and there is no context-specific field applied to the context. Properties specified at kubernetes level for all contexts is still applied.
This behavior maintains backwards compatibility but makes `allowed_contexts` redundant, paving the way to deprecate this field in the future.

cc. @romilbhardwaj  @cg505
