### ISSUE TITLE
SkyPilot failed to retrieve conda channels

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#5496]
I occasionally got this error when using skyserve. Noticed that I'm on a old branch (#4362) so it is possible that this is a solved issue, but just posted here in case it is sth new. YAML I used:

```yaml
name: multi-lb-llm

envs:
  # MODEL_NAME: meta-llama/Llama-3.2-3B-Instruct
  MODEL_NAME: meta-llama/Llama-3.1-8B-Instruct
  HF_TOKEN:

service:
  readiness_probe:
    # Don't use /v1/chat/completions as that will be
    # queued and it is possible to fail for timeout.
    path: /v1/models
  replicas: 12
  # TODO(tian): Change the config to a cloud-agnostic way.
  route53_hosted_zone: aws.cblmemo.net
  # Meta load balancing policy used to select the LB.
  load_balancing_policy: prefix_tree
  # load_balancing_policy: least_load
  # load_balancing_policy: round_robin
  external_load_balancers:
    - resources:
        cloud: aws
        region: us-east-2
      load_balancing_policy: prefix_tree
    - resources:
        cloud: aws
        region: ap-northeast-1
      load_balancing_policy: prefix_tree
    - resources:
        cloud: aws
        region: eu-central-1
      load_balancing_policy: prefix_tree
  # max_concurrent_requests: 50

resources:
  cloud: aws
  cpus: 16+
  disk_tier: high
  accelerators: L4:1
  ordered:
    - region: us-east-2
    - region: ap-northeast-1
    - region: eu-central-1
  ports: 8081

setup: |
  # pip install vllm==0.6.2
  # pip install transformers==4.48.3 "sglang[all]==0.4.3.post2" \
  #   --find-links https://flashinfer.ai/whl/cu124/torch2.4/flashinfer/
  # For cache report
  # pip install "sglang[all]>=0.4.5" \
  #   --find-links https://flashinfer.ai/whl/cu124/torch2.5/flashinfer-python

  uv venv -p 3.10
  source .venv/bin/activate
  uv pip install huggingface-hub==0.30.2
  # Parallel the installation and download the model.
  uv pip install setuptools==79.0.0 "sglang[all]==0.4.5" \
    --find-links https://flashinfer.ai/whl/cu124/torch2.5/flashinfer-python &
  huggingface-cli download $MODEL_NAME \
    --max-workers 32 \
    --include "*.safetensors"
  wait

run: |
  # vllm serve $MODEL_NAME \
  #   --port 8081 \
  #   --enable-prefix-caching \
  #   --tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE \
  #   --max-model-len 4096

  source .venv/bin/activate
  python -m sglang.launch_server \
    --model-path $MODEL_NAME \
    --port 8081 \
    --host 0.0.0.0 \
    --tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE \
    --enable-metrics \
    --enable-cache-report \
    --mem-fraction-static 0.8

```

error log:

```bash
I 05-05 18:03:26 replica_managers.py:144] Failed to launch the sky serve replica cluster with error: RuntimeError: Failed to run setup commands on an instance. (exit code 1). Error: ===== stdout ===== 
I 05-05 18:03:26 replica_managers.py:144] # >>> conda initialize >>>
I 05-05 18:03:26 replica_managers.py:144] 
I 05-05 18:03:26 replica_managers.py:144] CondaKeyError: 'channels': 'https://aws-ml-conda-ec2.s3.us-west-2.amazonaws.com' is not in the 'channels' key of the config file
I 05-05 18:03:26 replica_managers.py:144] 
I 05-05 18:03:26 replica_managers.py:144] PATH=/home/ubuntu/.local/bin:/home/ubuntu/.local/bin:/home/ubuntu/miniconda3/bin:/home/ubuntu/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
I 05-05 18:03:26 replica_managers.py:144] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:144] Audited 1 package in 1ms
I 05-05 18:03:26 replica_managers.py:144] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:144] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:144] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:144] warning: Skipping skypilot as it is not installed
I 05-05 18:03:26 replica_managers.py:144] warning: No packages to uninstall
I 05-05 18:03:26 replica_managers.py:144] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:144]   × Failed to read `skypilot @
I 05-05 18:03:26 replica_managers.py:144]   │ file:///home/ubuntu/.sky/wheels/b5f2198228b5ce429e7f3ce69b4b4994/skypilot-1.0.0.dev0-py3-none-any.whl`
I 05-05 18:03:26 replica_managers.py:144]   ├─▶ Failed to read metadata:
I 05-05 18:03:26 replica_managers.py:144]   │   `/home/ubuntu/.sky/wheels/b5f2198228b5ce429e7f3ce69b4b4994/skypilot-1.0.0.dev0-py3-none-any.whl`
I 05-05 18:03:26 replica_managers.py:144]   ├─▶ Failed to read from zip file
I 05-05 18:03:26 replica_managers.py:144]   ╰─▶ unable to locate the end of central directory record
I 05-05 18:03:26 replica_managers.py:144] 
I 05-05 18:03:26 replica_managers.py:144] ===== stderr =====)
I 05-05 18:03:26 replica_managers.py:147]   Traceback: Traceback (most recent call last):
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/serve/replica_managers.py", line 123, in launch_cluster
I 05-05 18:03:26 replica_managers.py:147]     execution.launch(task,
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 454, in _record
I 05-05 18:03:26 replica_managers.py:147]     return f(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 454, in _record
I 05-05 18:03:26 replica_managers.py:147]     return f(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/execution.py", line 532, in launch
I 05-05 18:03:26 replica_managers.py:147]     return _execute(
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/execution.py", line 311, in _execute
I 05-05 18:03:26 replica_managers.py:147]     handle = backend.provision(
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 454, in _record
I 05-05 18:03:26 replica_managers.py:147]     return f(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 434, in _record
I 05-05 18:03:26 replica_managers.py:147]     return f(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/backends/backend.py", line 84, in provision
I 05-05 18:03:26 replica_managers.py:147]     return self._provision(task, to_provision, dryrun, stream_logs,
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2978, in _provision
I 05-05 18:03:26 replica_managers.py:147]     cluster_info = provisioner.post_provision_runtime_setup(
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 454, in _record
I 05-05 18:03:26 replica_managers.py:147]     return f(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/provisioner.py", line 659, in post_provision_runtime_setup
I 05-05 18:03:26 replica_managers.py:147]     return _post_provision_setup(cloud_name,
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/provisioner.py", line 504, in _post_provision_setup
I 05-05 18:03:26 replica_managers.py:147]     instance_setup.setup_runtime_on_cluster(
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/common.py", line 294, in wrapper
I 05-05 18:03:26 replica_managers.py:147]     return func(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 454, in _record
I 05-05 18:03:26 replica_managers.py:147]     return f(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 253, in setup_runtime_on_cluster
I 05-05 18:03:26 replica_managers.py:147]     _parallel_ssh_with_cache(_setup_node,
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 166, in _parallel_ssh_with_cache
I 05-05 18:03:26 replica_managers.py:147]     return [future.result() for future in results]
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 166, in <listcomp>
I 05-05 18:03:26 replica_managers.py:147]     return [future.result() for future in results]
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 458, in result
I 05-05 18:03:26 replica_managers.py:147]     return self.__get_result()
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
I 05-05 18:03:26 replica_managers.py:147]     raise self._exception
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
I 05-05 18:03:26 replica_managers.py:147]     result = self.fn(*self.args, **self.kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/metadata_utils.py", line 45, in wrapper
I 05-05 18:03:26 replica_managers.py:147]     return function(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 112, in retry
I 05-05 18:03:26 replica_managers.py:147]     return func(*args, **kwargs)
I 05-05 18:03:26 replica_managers.py:147]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 247, in _setup_node
I 05-05 18:03:26 replica_managers.py:147]     raise RuntimeError(
I 05-05 18:03:26 replica_managers.py:147] RuntimeError: Failed to run setup commands on an instance. (exit code 1). Error: ===== stdout ===== 
I 05-05 18:03:26 replica_managers.py:147] # >>> conda initialize >>>
I 05-05 18:03:26 replica_managers.py:147] 
I 05-05 18:03:26 replica_managers.py:147] CondaKeyError: 'channels': 'https://aws-ml-conda-ec2.s3.us-west-2.amazonaws.com' is not in the 'channels' key of the config file
I 05-05 18:03:26 replica_managers.py:147] 
I 05-05 18:03:26 replica_managers.py:147] PATH=/home/ubuntu/.local/bin:/home/ubuntu/.local/bin:/home/ubuntu/miniconda3/bin:/home/ubuntu/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
I 05-05 18:03:26 replica_managers.py:147] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:147] Audited 1 package in 1ms
I 05-05 18:03:26 replica_managers.py:147] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:147] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:147] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:147] warning: Skipping skypilot as it is not installed
I 05-05 18:03:26 replica_managers.py:147] warning: No packages to uninstall
I 05-05 18:03:26 replica_managers.py:147] Using Python 3.10.15 environment at: skypilot-runtime
I 05-05 18:03:26 replica_managers.py:147]   × Failed to read `skypilot @
I 05-05 18:03:26 replica_managers.py:147]   │ file:///home/ubuntu/.sky/wheels/b5f2198228b5ce429e7f3ce69b4b4994/skypilot-1.0.0.dev0-py3-none-any.whl`
I 05-05 18:03:26 replica_managers.py:147]   ├─▶ Failed to read metadata:
I 05-05 18:03:26 replica_managers.py:147]   │   `/home/ubuntu/.sky/wheels/b5f2198228b5ce429e7f3ce69b4b4994/skypilot-1.0.0.dev0-py3-none-any.whl`
I 05-05 18:03:26 replica_managers.py:147]   ├─▶ Failed to read from zip file
I 05-05 18:03:26 replica_managers.py:147]   ╰─▶ unable to locate the end of central directory record
I 05-05 18:03:26 replica_managers.py:147] 
I 05-05 18:03:26 replica_managers.py:147] ===== stderr =====
```
