### ISSUE TITLE
[RunPod] `envs` section in `sky serve` deployments not being forwarded to RunPod instances running private images

### ISSUE THREAD

**Issue by turtlebasket** [skypilot-org/skypilot#5545]
Happening on nightly `1.0.0.dev20250506`. Basic repro is as follows (both use `--env-file .env` to populate envvars)—

This general pattern works (service starts, and `os.getenv / os.environ` can find required envvars):

```yaml
service:
  readiness_probe: /healthcheck
  replica_policy:
    min_replicas: 2
    max_replicas: 12
    target_qps_per_replica: 100
  tls:
    certfile: certs/skyserve.crt
    keyfile: certs/skyserve.key

resources:
  image_id: ubuntu:24.04 
  cloud: runpod
  region: US
  ports: 8000
  cpus: 4+
  memory: 8+
  disk_size: 32
  accelerators:
    - RTX6000-Ada
  use_spot: false

envs:
  HF_TOKEN:
  HF_MODEL:
  AUTH_TOKEN:

setup: |
  # basically replicating the Dockerfile contents;
  # install requirements, etc.

run: |
  python3 main.py
```

This pattern does not (service starts, but `os.getenv / os.environ` *cannot* find required envvars):

```yaml
service:
  readiness_probe: /healthcheck
  replica_policy:
    min_replicas: 2
    max_replicas: 12
    target_qps_per_replica: 100
  tls:
    certfile: certs/skyserve.crt
    keyfile: certs/skyserve.key

resources:
  image_id: # <private image using debian bookworm base>
  cloud: runpod
  region: US
  ports: 8000
  cpus: 4+
  memory: 8+
  disk_size: 32
  accelerators:
    - RTX6000-Ada
  use_spot: false

envs:
  SKYPILOT_DOCKER_SERVER: ghcr.io
  SKYPILOT_DOCKER_USERNAME:
  SKYPILOT_DOCKER_PASSWORD:
  HF_TOKEN:
  HF_MODEL:
  AUTH_TOKEN:

run: |
  /app/docker-entrypoint.sh
```

The private image *is* pulled and run successfully, so to me this suggests it's a problem with the step of forwarding the remaining env vars to the RunPod instance.
