### ISSUE TITLE
[feature request] Add conda, pip, apt blocks in SkyPilot YAML

### ISSUE THREAD

**Issue by paras-genmo** [skypilot-org/skypilot#5569]
SkyPilot users frequently spend many setup steps repeatedly installing packages. Allowing direct specification of dependencies in SkyPilot YAML would greatly simplify user workflows while improving reliability and reproducibility.

It would be great to add support for optional conda: and/or pip: blocks to SkyPilot YAML, using familiar Conda environment YAML syntax. 

```
setup:
  conda:
    channels:
      - conda-forge
    dependencies:
      - python=3.10
      - pytorch
      - torchaudio
      - pip:
          - gradio
          - soundfile
```

Or simpler pip-only syntax:
```
setup:
  pip:
    - torch
    - torchvision
    - gradio
```

SkyPilot could internally use mamba (for Conda) or uv (for pip) for fast and parallel dependency installs, significantly reducing setup time.
