### ISSUE TITLE
[jobs] Allow jobs controller to be high availability like serve controller

### ISSUE THREAD

**Issue by clayrosenthal** [skypilot-org/skypilot#5791]
For the sky serve controller you can use a kubernetes deployment to make sure it stays up: 
```yaml
serve:
  # NOTE: these settings only take effect for a new SkyServe controller, not if
  # you have an existing one.
  controller:
    # Enable high availability mode for the controller (optional).
    #
    # When set to true, the controller will be deployed with high availability
    # capabilities on Kubernetes using Deployments. This allows the controller and load balancer
    # to automatically recover from failures (e.g., node failures, pod crashes)
    # and maintain service continuity.
    #
    # NOTE: This feature is ONLY supported when Kubernetes cloud is enabled. To enable kubernetes, see :ref:`Kubernetes Setup <kubernetes-setup>`.
    # The service controller cluster will be scheduled to kubernetes. The k8s deployment needs to be always-on to keep the controller running. If using a local kubernetes deployment (e.g. `sky local up`), keeping the laptop/machines up is required.
    # When enabled:
    # - The controller is deployed as a Kubernetes Deployment instead of a Pod
    # - Automatic pod rescheduling and recovery is handled by Kubernetes
    #
    # Default: false.
    high_availability: true
```

but for the jobs controller, there is no such option:
```yaml
jobs:
  bucket: s3://my-bucket/
  controller:
    resources:  # same spec as 'resources' in a task YAML
      infra: gcp/us-central1
      cpus: 4+  # number of vCPUs, max concurrent spot jobs = 2 * cpus
      disk_size: 100
    autostop:
      idle_minutes: 10
      down: false  # use with caution!
```

Could you add an option to the jobs controller to let it be launched as a deployment as well?
