### ISSUE TITLE
Support for AWS Local Zones

### ISSUE THREAD

**Issue by rhbelson** [skypilot-org/skypilot#5919]
**Issue Description:** Support for Local Zones (or any AZ that is not within the parent region) is not supported today.

When running `sky launch demo-workload.yaml`, I get an error "ValueError: Invalid zone 'us-west-2-lax-1a' for region 'us-west-2'". This is, in fact, a valid availability zone and can't think of any reason it can't be supported, given no change to underlying AWS networking (support for Public IPs + Internet Gateway).

```
 cat demo-workload.yaml
resources:
  # Optional; if left out, automatically pick the cheapest cloud.
  infra: aws
  # 8x NVIDIA A100 GPU
  accelerators: A100:1

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: .

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  echo "Hello, SkyPilot!"
  conda env list

resources:
  # infra: aws/us-west-2  # Use a particular region.
  infra: aws/*/us-west-2-lax-1b
  infra: aws/*/us-west-2-lax-1a
  infra: aws/*/us-west-2-las-1a
```
