### ISSUE TITLE
[GCP] Support READ_ONLY mode for `hyperdisk-ml` volumes

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#5953]
Users need high perf volumes for data read/write. The recommended way to get high perf dataset reads on GCP is using [hyperdisk-ml](https://cloud.google.com/compute/docs/disks/hd-types/hyperdisk-ml).

When put in READ_ONLY mode, it can be simultaneously mounted to multiple (upto 2500) instances with upto 19,200,000 IOPS and 1,200,000 MiB/s throughput.

SkyPilot currently does not support mounting hyperdisk-ml to multiple nodes:
```
file_mounts:
  /mnt/data:
    name: sky-vol-test-ml2  # Existing bucket created from cloud console
    store: volume
    persistent: true

resources:
  # Must specify cloud, and region or zone.
  # These need to match the volume's location.
  instance_type: c3-standard-88
  cloud: gcp
  zone: us-central1-a
```

```
$ sky launch -c vol4 --num-nodes 2 volumes.yaml
YAML to run: volumes.yaml
Considered resources (2 nodes):
-------------------------------------------------------------------------------------
 INFRA                 INSTANCE         vCPUs   Mem(GB)   GPUS   COST ($)   CHOSEN
-------------------------------------------------------------------------------------
 GCP (us-central1-a)   c3-standard-88   88      352       -      8.87          ✔
-------------------------------------------------------------------------------------
Launching a new cluster 'vol4'. Proceed? [Y/n]:
⚙︎ Launching on GCP us-central1 (us-central1-a).
W 06-10 12:43:06 instance_utils.py:113] Got return code 'badRequest' in us-central1-a: 'The disk cannot be attached with READ_WRITE mode'
sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-central1-a for {GCP(c3-standard-88)}.
```
