### ISSUE TITLE
SkyPilot losing track of L40S RunPod instances

### ISSUE THREAD

**Issue by turtlebasket** [skypilot-org/skypilot#6051]
(on nightly `1.0.0.dev20250610`)

Not sure if "losing track of" is the right phrasing for this, but using the following config:

```yaml
service:
  readiness_probe: /healthcheck
  replica_policy:
    min_replicas: 1
    max_replicas: 4
    target_qps_per_replica: 20
  tls:
    certfile: certs/skyserve.crt
    keyfile: certs/skyserve.key

resources:
  image_id: docker:ghcr.io/<our private image>
  ports: 8000
  cpus: 4+
  memory: 8+
  disk_size: 32
  use_spot: false
  any_of:
    - cloud: runpod
      region: US
      accelerators: L40S:1

envs:
  SKYPILOT_DOCKER_SERVER: ghcr.io
  SKYPILOT_DOCKER_USERNAME:
  SKYPILOT_DOCKER_PASSWORD:
  # ...

run: |
  /app/docker-entrypoint.sh
```

The spinup completes correctly, and I can see that it considers the correct accelerator (although the price seems to be off by a factor of two for some reason).

```
---------------------------------------------------------------------------------------------
 INFRA         INSTANCE                vCPUs   Mem(GB)   GPUS            COST ($)   CHOSEN   
---------------------------------------------------------------------------------------------
 RunPod (US)   1x_L40S_SECURE          12      62        L40S:1          0.43          ✔     
---------------------------------------------------------------------------------------------
```

Checking the status during spinup:

```
$ sky serve status
Services
NAME              VERSION  UPTIME  STATUS      REPLICAS  ENDPOINT
sky-service-96b1  -        -       NO_REPLICA  0/1       https://<DOKS LB IP>:30001

Service Replicas
SERVICE_NAME      ID  VERSION  ENDPOINT  LAUNCHED  INFRA  RESOURCES  STATUS
sky-service-96b1  1   1        -         -         -      -          PENDING
```

...seems to work, but after waiting 1-2 minutes:

```
$ sky serve status
ValueError: No instance type 1x_L40S_SECURE found.
```

This happens specifically with L40S instances.
