### ISSUE TITLE
[Kubernetes] Use native k8s `StatefulSet` for sky clusters

### ISSUE THREAD

**Issue by clayrosenthal** [skypilot-org/skypilot#6107]
Currently when launching clusters on kubernetes they are just Pods, which can get disrupted by a node being cycled, losing the cluster. If [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/)'s were used, the cluster would be re-scheduled on a new node and would hopefully be able to continue. 

Based on StatefulSets description:

>  StatefulSets are valuable for applications that require one or more of the following.
> 
>     Stable, unique network identifiers.
>     Stable, persistent storage.
>     Ordered, graceful deployment and scaling.
>     Ordered, automated rolling updates.
> 
> In the above, stable is synonymous with persistence across Pod (re)scheduling.

I think they are the most accurate analog to the average sky cluster.

You can also use the `VolumeClaimTemplates` for `disk_size` resource config:
```yaml
volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
```

Perhaps also using `disk_type` for `storageClassName`
