### ISSUE TITLE
Sky storage upload proceeds without confirmation when using `sky launch`

### ISSUE THREAD

**Issue by gmittal** [skypilot-org/skypilot#681]
I have the following yaml:
```
name: my-task
workdir: .
num_nodes: 4

resources:
  cloud: aws
  accelerators: V100:4
  accelerator_args:
    tf_version: 2.5.0
  use_spot: False
  disk_size: 256

file_mounts:
  /remote/path/datasets: sky

  /datasets-storage:
    name: sky-dataset2
    source: .
    force_stores: [s3]  # Could be [s3, gcs], [gcs] default: None
    persistent: True  # Defaults to True, can be set to false.

  # /datasets-s3: s3://sky-dataset

setup: |
  echo "Begin setup."
  pip install -r requirements.txt
  echo "Setup complete."

run: |
  echo "Beginning task."
  python train.py
```

I ran:
```
sky launch task.yaml
```

and it began uploading instantly rather than waiting for my approval through the usual confirmation prompt.

```
sky ❯ sky launch task.yaml
Task from YAML spec: task.yaml
I 04-01 15:43:59 storage.py:198] Detected existing storage object, loading Storage: sky-dataset2
I 04-01 15:43:59 storage.py:222] Verifying Bucket Contents: S3
^C
Aborted!
```
