### ISSUE TITLE
Overwriting the accelerators produces wrong optimization information

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#697]
We do not have the check for the accelerators when `--gpus` is override by CLI.
```
sky launch -c test task.yml --gpus V100
```
```
# task.yml
resources:
  cloud: aws
  accelerators: T4
  instance_type: g4dn.4xlarge
```
