### ISSUE TITLE
Tail Logs with Excessive Throughput

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#723]
```
I 04-06 17:44:16 cloud_vm_ray_backend.py:1602] To view detailed progress: tail -n100 -f ~/sky_logs/sky-2022-04-06-17-40-59-023422/file_mounts.log
I 04-06 17:44:16 cloud_vm_ray_backend.py:1556] Syncing (to 1 node): s3://imagenet-bucket -> /tmp/imagenet
```
Running `tail -n100 -f ~/sky_logs/sky-2022-04-06-17-40-59-023422/file_mounts.log` will hang and output nothing during Upload.

## Reproduce: 
Any config with:
```
file_mounts:
  /tmp/imagenet:
    source: s3://imagenet-bucket
    mode: COPY
```
