### ISSUE TITLE
[Storage] Suprising behavior when switching from MOUNT to COPY mode

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#786]
I have a task with the following yaml, which works fine with the default MOUNT mode:
```
file_mounts:
  /imagenet:
    name: imagenet-bucket
```
However, when I added `mode: COPY` to copy the data to the disk, it raises the following error, which is a bit surprising to me. `sky.exceptions.StorageSourceError: Storage source must be specified when using COPY mode.`

Do you think we can allow this @romilbhardwaj ?
```
file_mounts:
  /imagenet:
    name: imagenet-bucket
    mode: COPY
```
