### ISSUE TITLE
Archive the logs for spot jobs to persistent storage.

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#800]

**Comment by Michaelvll** [comment]
This is requested by the uesr:
> Is there a way to make the spot controller proactively sync logs from the launched clusters (or for these text logs to be uploaded to some s3 location, configurable)? I’m trying to debug some issues where I’m still getting no text logs on some of the runs, possibly a follow up episode of the s3 / log flushing issue (I changed it so that different ranks log to different files, but still using append mode).
Right now I can do sky logs -s on jobs that are still running, but for the ones that are stopped (or for spot jobs, the previous runs before pre-emption) seems like the text logs are done for good.

**Comment by infwinston** [comment]
Ah I should come back to this. One thing that requires some discussion is that what's the lifecycle of user's log? Should we upload the logs to S3 by default and when should we clean them up? or introduce a new command like `sky spot log --cleanup`?

**Comment by Michaelvll** [comment]
This PR is being solved in #1697

**Comment by concretevitamin** [comment]
Quick experiment with another approach: use a cloud-specific logging service.

Take GCP. We can log a spot job's log to Cloud Logging as follows. (AWS has CloudWatch Logs.) 

In the spot cluster (assuming 1 node for now):
- Install Ops Agent
```
curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
sudo bash add-google-cloud-ops-agent-repo.sh --also-install
```
- Point the Agent to the running spot task's log file:
```
sudo vim /etc/google-cloud-ops-agent/config.yaml
# content:
logging:
  receivers:
    custom_logs:
      type: files
      include_paths:
        - /home/gcpuser/sky_logs/sky-2023-06-23-05-01-51-679044/run.log
  service:
    pipelines:
      default_pipeline:
        receivers: [custom_logs]
```
- Restart the Agent
```
sudo service google-cloud-ops-agent restart
```
- Note: this required some logWrite permission. I temporarily hacked around it by adding "Logging Admin" to our service account.

This will then stream the log file to Cloud Logging console. It should be persistent (not tied to the spot cluster's lifetime). 
<img width="778" alt="Screen Shot 2023-06-22 at 22 42 41" src="https://github.com/skypilot-org/skypilot/assets/592670/18c0cb95-0641-4c59-8bb5-3aca76b48d6f">


Many open questions: 
- This vs. cloud object store.
  - Pricing, usability, etc.
- How to label/tag these log entires correctly so that users can quickly look up a job/job_id's logs, across recoveries.
