### ISSUE TITLE
[Storage] `COPY` mode mounting fails for existing Storage objects

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#856]
From @concretevitamin:

I’m trying to test this out:
```
file_mounts:
  /checkpoints:
    name: my-sky-ckpts
    mode: MOUNT
```
this works.

Then I want to add a variant of COPY, so I intuitively change mode
```
file_mounts:
  /checkpoints:
    name: my-sky-ckpts
    mode: COPY 
```
which prints
`sky.exceptions.StorageSourceError: Storage source must be specified when using COPY mode.`
I think you explained once why this is the case.  But from a UX perspective, this seems very surprising to me.
