### ISSUE TITLE
`$(nproc)` in setup and run sections

### ISSUE THREAD

**Issue by WoosukKwon** [skypilot-org/skypilot#951]
My task on a m6i.2xlarge instance
```yaml
name: nproc

resources:
  cloud: aws

setup: |
  echo "setup $(nproc)"

run: |
  echo "run $(nproc)"
```
returns 
```
setup 1
run 1
```
, while the correct number of CPUs is 8.

To my understanding, the result is because we set `OMP_NUM_THREADS=1` at setup time and allocate 0.5 CPU to each task at run time. While I don't know why Sky needs such constraints, I believe they can confuse many users. E.g., `make -j$(nproc)` or `python train.py --num_workers $(nproc)` can silently lead to very bad performance.

I think we have two solutions:
1. Override `nproc` with `nproc --all`.
2. Provide a special environment variable `SKY_NUM_CPUS` to replace `$(nproc)`.

I'm not sure which one is better. The first solution is transparent to users but there can be corner cases. The second one is more a manual solution.
