### ISSUE TITLE
YAML support for sky.Storage

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#96]
Sky storage (#63) will also require YAML support so Storage objects can be defined as a part of the YAML schema. Maybe something like:

```
name: resnet-app
workdir: ~/Downloads/tpu

resources:
  cloud: aws
  instance_type: p3.2xlarge

storage:
  name: imagenet-bucket
  source_path=s3://imagenet-bucket
  mount_path=/imagenet/
```
